// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: country/v1/country.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request/Response messages
type CreateCountryRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Code           string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	NameEn         string                 `protobuf:"bytes,3,opt,name=name_en,json=nameEn,proto3" json:"name_en,omitempty"`
	Region         string                 `protobuf:"bytes,4,opt,name=region,proto3" json:"region,omitempty"`
	SubRegion      string                 `protobuf:"bytes,5,opt,name=sub_region,json=subRegion,proto3" json:"sub_region,omitempty"`
	CurrencyCode   string                 `protobuf:"bytes,6,opt,name=currency_code,json=currencyCode,proto3" json:"currency_code,omitempty"`
	CurrencySymbol string                 `protobuf:"bytes,7,opt,name=currency_symbol,json=currencySymbol,proto3" json:"currency_symbol,omitempty"`
	PhoneCode      string                 `protobuf:"bytes,8,opt,name=phone_code,json=phoneCode,proto3" json:"phone_code,omitempty"`
	TimeZone       string                 `protobuf:"bytes,9,opt,name=time_zone,json=timeZone,proto3" json:"time_zone,omitempty"`
	Flag           string                 `protobuf:"bytes,10,opt,name=flag,proto3" json:"flag,omitempty"`
	Capital        string                 `protobuf:"bytes,11,opt,name=capital,proto3" json:"capital,omitempty"`
	Population     int64                  `protobuf:"varint,12,opt,name=population,proto3" json:"population,omitempty"`
	Iso3166Alpha3  string                 `protobuf:"bytes,13,opt,name=iso3166_alpha3,json=iso3166Alpha3,proto3" json:"iso3166_alpha3,omitempty"`
	Iso3166Numeric string                 `protobuf:"bytes,14,opt,name=iso3166_numeric,json=iso3166Numeric,proto3" json:"iso3166_numeric,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateCountryRequest) Reset() {
	*x = CreateCountryRequest{}
	mi := &file_country_v1_country_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCountryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCountryRequest) ProtoMessage() {}

func (x *CreateCountryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_country_v1_country_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCountryRequest.ProtoReflect.Descriptor instead.
func (*CreateCountryRequest) Descriptor() ([]byte, []int) {
	return file_country_v1_country_proto_rawDescGZIP(), []int{0}
}

func (x *CreateCountryRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CreateCountryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCountryRequest) GetNameEn() string {
	if x != nil {
		return x.NameEn
	}
	return ""
}

func (x *CreateCountryRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *CreateCountryRequest) GetSubRegion() string {
	if x != nil {
		return x.SubRegion
	}
	return ""
}

func (x *CreateCountryRequest) GetCurrencyCode() string {
	if x != nil {
		return x.CurrencyCode
	}
	return ""
}

func (x *CreateCountryRequest) GetCurrencySymbol() string {
	if x != nil {
		return x.CurrencySymbol
	}
	return ""
}

func (x *CreateCountryRequest) GetPhoneCode() string {
	if x != nil {
		return x.PhoneCode
	}
	return ""
}

func (x *CreateCountryRequest) GetTimeZone() string {
	if x != nil {
		return x.TimeZone
	}
	return ""
}

func (x *CreateCountryRequest) GetFlag() string {
	if x != nil {
		return x.Flag
	}
	return ""
}

func (x *CreateCountryRequest) GetCapital() string {
	if x != nil {
		return x.Capital
	}
	return ""
}

func (x *CreateCountryRequest) GetPopulation() int64 {
	if x != nil {
		return x.Population
	}
	return 0
}

func (x *CreateCountryRequest) GetIso3166Alpha3() string {
	if x != nil {
		return x.Iso3166Alpha3
	}
	return ""
}

func (x *CreateCountryRequest) GetIso3166Numeric() string {
	if x != nil {
		return x.Iso3166Numeric
	}
	return ""
}

type CreateCountryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Country       *Country               `protobuf:"bytes,1,opt,name=country,proto3" json:"country,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCountryResponse) Reset() {
	*x = CreateCountryResponse{}
	mi := &file_country_v1_country_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCountryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCountryResponse) ProtoMessage() {}

func (x *CreateCountryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_country_v1_country_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCountryResponse.ProtoReflect.Descriptor instead.
func (*CreateCountryResponse) Descriptor() ([]byte, []int) {
	return file_country_v1_country_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCountryResponse) GetCountry() *Country {
	if x != nil {
		return x.Country
	}
	return nil
}

type UpdateCountryRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Code           string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Name           string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	NameEn         string                 `protobuf:"bytes,4,opt,name=name_en,json=nameEn,proto3" json:"name_en,omitempty"`
	Region         string                 `protobuf:"bytes,5,opt,name=region,proto3" json:"region,omitempty"`
	SubRegion      string                 `protobuf:"bytes,6,opt,name=sub_region,json=subRegion,proto3" json:"sub_region,omitempty"`
	CurrencyCode   string                 `protobuf:"bytes,7,opt,name=currency_code,json=currencyCode,proto3" json:"currency_code,omitempty"`
	CurrencySymbol string                 `protobuf:"bytes,8,opt,name=currency_symbol,json=currencySymbol,proto3" json:"currency_symbol,omitempty"`
	PhoneCode      string                 `protobuf:"bytes,9,opt,name=phone_code,json=phoneCode,proto3" json:"phone_code,omitempty"`
	TimeZone       string                 `protobuf:"bytes,10,opt,name=time_zone,json=timeZone,proto3" json:"time_zone,omitempty"`
	Flag           string                 `protobuf:"bytes,11,opt,name=flag,proto3" json:"flag,omitempty"`
	Capital        string                 `protobuf:"bytes,12,opt,name=capital,proto3" json:"capital,omitempty"`
	Population     int64                  `protobuf:"varint,13,opt,name=population,proto3" json:"population,omitempty"`
	Iso3166Alpha3  string                 `protobuf:"bytes,14,opt,name=iso3166_alpha3,json=iso3166Alpha3,proto3" json:"iso3166_alpha3,omitempty"`
	Iso3166Numeric string                 `protobuf:"bytes,15,opt,name=iso3166_numeric,json=iso3166Numeric,proto3" json:"iso3166_numeric,omitempty"`
	Status         string                 `protobuf:"bytes,16,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateCountryRequest) Reset() {
	*x = UpdateCountryRequest{}
	mi := &file_country_v1_country_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCountryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCountryRequest) ProtoMessage() {}

func (x *UpdateCountryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_country_v1_country_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCountryRequest.ProtoReflect.Descriptor instead.
func (*UpdateCountryRequest) Descriptor() ([]byte, []int) {
	return file_country_v1_country_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateCountryRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateCountryRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *UpdateCountryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateCountryRequest) GetNameEn() string {
	if x != nil {
		return x.NameEn
	}
	return ""
}

func (x *UpdateCountryRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *UpdateCountryRequest) GetSubRegion() string {
	if x != nil {
		return x.SubRegion
	}
	return ""
}

func (x *UpdateCountryRequest) GetCurrencyCode() string {
	if x != nil {
		return x.CurrencyCode
	}
	return ""
}

func (x *UpdateCountryRequest) GetCurrencySymbol() string {
	if x != nil {
		return x.CurrencySymbol
	}
	return ""
}

func (x *UpdateCountryRequest) GetPhoneCode() string {
	if x != nil {
		return x.PhoneCode
	}
	return ""
}

func (x *UpdateCountryRequest) GetTimeZone() string {
	if x != nil {
		return x.TimeZone
	}
	return ""
}

func (x *UpdateCountryRequest) GetFlag() string {
	if x != nil {
		return x.Flag
	}
	return ""
}

func (x *UpdateCountryRequest) GetCapital() string {
	if x != nil {
		return x.Capital
	}
	return ""
}

func (x *UpdateCountryRequest) GetPopulation() int64 {
	if x != nil {
		return x.Population
	}
	return 0
}

func (x *UpdateCountryRequest) GetIso3166Alpha3() string {
	if x != nil {
		return x.Iso3166Alpha3
	}
	return ""
}

func (x *UpdateCountryRequest) GetIso3166Numeric() string {
	if x != nil {
		return x.Iso3166Numeric
	}
	return ""
}

func (x *UpdateCountryRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UpdateCountryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Country       *Country               `protobuf:"bytes,1,opt,name=country,proto3" json:"country,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCountryResponse) Reset() {
	*x = UpdateCountryResponse{}
	mi := &file_country_v1_country_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCountryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCountryResponse) ProtoMessage() {}

func (x *UpdateCountryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_country_v1_country_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCountryResponse.ProtoReflect.Descriptor instead.
func (*UpdateCountryResponse) Descriptor() ([]byte, []int) {
	return file_country_v1_country_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateCountryResponse) GetCountry() *Country {
	if x != nil {
		return x.Country
	}
	return nil
}

type DeleteCountryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCountryRequest) Reset() {
	*x = DeleteCountryRequest{}
	mi := &file_country_v1_country_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCountryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCountryRequest) ProtoMessage() {}

func (x *DeleteCountryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_country_v1_country_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCountryRequest.ProtoReflect.Descriptor instead.
func (*DeleteCountryRequest) Descriptor() ([]byte, []int) {
	return file_country_v1_country_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteCountryRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteCountryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCountryResponse) Reset() {
	*x = DeleteCountryResponse{}
	mi := &file_country_v1_country_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCountryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCountryResponse) ProtoMessage() {}

func (x *DeleteCountryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_country_v1_country_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCountryResponse.ProtoReflect.Descriptor instead.
func (*DeleteCountryResponse) Descriptor() ([]byte, []int) {
	return file_country_v1_country_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteCountryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetCountryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCountryRequest) Reset() {
	*x = GetCountryRequest{}
	mi := &file_country_v1_country_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCountryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCountryRequest) ProtoMessage() {}

func (x *GetCountryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_country_v1_country_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCountryRequest.ProtoReflect.Descriptor instead.
func (*GetCountryRequest) Descriptor() ([]byte, []int) {
	return file_country_v1_country_proto_rawDescGZIP(), []int{6}
}

func (x *GetCountryRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetCountryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Country       *Country               `protobuf:"bytes,1,opt,name=country,proto3" json:"country,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCountryResponse) Reset() {
	*x = GetCountryResponse{}
	mi := &file_country_v1_country_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCountryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCountryResponse) ProtoMessage() {}

func (x *GetCountryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_country_v1_country_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCountryResponse.ProtoReflect.Descriptor instead.
func (*GetCountryResponse) Descriptor() ([]byte, []int) {
	return file_country_v1_country_proto_rawDescGZIP(), []int{7}
}

func (x *GetCountryResponse) GetCountry() *Country {
	if x != nil {
		return x.Country
	}
	return nil
}

type GetCountryByCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCountryByCodeRequest) Reset() {
	*x = GetCountryByCodeRequest{}
	mi := &file_country_v1_country_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCountryByCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCountryByCodeRequest) ProtoMessage() {}

func (x *GetCountryByCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_country_v1_country_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCountryByCodeRequest.ProtoReflect.Descriptor instead.
func (*GetCountryByCodeRequest) Descriptor() ([]byte, []int) {
	return file_country_v1_country_proto_rawDescGZIP(), []int{8}
}

func (x *GetCountryByCodeRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type GetCountryByCodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Country       *Country               `protobuf:"bytes,1,opt,name=country,proto3" json:"country,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCountryByCodeResponse) Reset() {
	*x = GetCountryByCodeResponse{}
	mi := &file_country_v1_country_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCountryByCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCountryByCodeResponse) ProtoMessage() {}

func (x *GetCountryByCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_country_v1_country_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCountryByCodeResponse.ProtoReflect.Descriptor instead.
func (*GetCountryByCodeResponse) Descriptor() ([]byte, []int) {
	return file_country_v1_country_proto_rawDescGZIP(), []int{9}
}

func (x *GetCountryByCodeResponse) GetCountry() *Country {
	if x != nil {
		return x.Country
	}
	return nil
}

type ListCountriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Search        string                 `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	Region        string                 `protobuf:"bytes,4,opt,name=region,proto3" json:"region,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Code          string                 `protobuf:"bytes,6,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCountriesRequest) Reset() {
	*x = ListCountriesRequest{}
	mi := &file_country_v1_country_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCountriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCountriesRequest) ProtoMessage() {}

func (x *ListCountriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_country_v1_country_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCountriesRequest.ProtoReflect.Descriptor instead.
func (*ListCountriesRequest) Descriptor() ([]byte, []int) {
	return file_country_v1_country_proto_rawDescGZIP(), []int{10}
}

func (x *ListCountriesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListCountriesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListCountriesRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *ListCountriesRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *ListCountriesRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListCountriesRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type ListCountriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Countries     []*Country             `protobuf:"bytes,1,rep,name=countries,proto3" json:"countries,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCountriesResponse) Reset() {
	*x = ListCountriesResponse{}
	mi := &file_country_v1_country_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCountriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCountriesResponse) ProtoMessage() {}

func (x *ListCountriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_country_v1_country_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCountriesResponse.ProtoReflect.Descriptor instead.
func (*ListCountriesResponse) Descriptor() ([]byte, []int) {
	return file_country_v1_country_proto_rawDescGZIP(), []int{11}
}

func (x *ListCountriesResponse) GetCountries() []*Country {
	if x != nil {
		return x.Countries
	}
	return nil
}

func (x *ListCountriesResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type SearchCountriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchCountriesRequest) Reset() {
	*x = SearchCountriesRequest{}
	mi := &file_country_v1_country_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchCountriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchCountriesRequest) ProtoMessage() {}

func (x *SearchCountriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_country_v1_country_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchCountriesRequest.ProtoReflect.Descriptor instead.
func (*SearchCountriesRequest) Descriptor() ([]byte, []int) {
	return file_country_v1_country_proto_rawDescGZIP(), []int{12}
}

func (x *SearchCountriesRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type SearchCountriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Countries     []*Country             `protobuf:"bytes,1,rep,name=countries,proto3" json:"countries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchCountriesResponse) Reset() {
	*x = SearchCountriesResponse{}
	mi := &file_country_v1_country_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchCountriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchCountriesResponse) ProtoMessage() {}

func (x *SearchCountriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_country_v1_country_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchCountriesResponse.ProtoReflect.Descriptor instead.
func (*SearchCountriesResponse) Descriptor() ([]byte, []int) {
	return file_country_v1_country_proto_rawDescGZIP(), []int{13}
}

func (x *SearchCountriesResponse) GetCountries() []*Country {
	if x != nil {
		return x.Countries
	}
	return nil
}

type Country struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Code           string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Name           string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	NameEn         string                 `protobuf:"bytes,4,opt,name=name_en,json=nameEn,proto3" json:"name_en,omitempty"`
	Region         string                 `protobuf:"bytes,5,opt,name=region,proto3" json:"region,omitempty"`
	SubRegion      string                 `protobuf:"bytes,6,opt,name=sub_region,json=subRegion,proto3" json:"sub_region,omitempty"`
	CurrencyCode   string                 `protobuf:"bytes,7,opt,name=currency_code,json=currencyCode,proto3" json:"currency_code,omitempty"`
	CurrencySymbol string                 `protobuf:"bytes,8,opt,name=currency_symbol,json=currencySymbol,proto3" json:"currency_symbol,omitempty"`
	PhoneCode      string                 `protobuf:"bytes,9,opt,name=phone_code,json=phoneCode,proto3" json:"phone_code,omitempty"`
	TimeZone       string                 `protobuf:"bytes,10,opt,name=time_zone,json=timeZone,proto3" json:"time_zone,omitempty"`
	Flag           string                 `protobuf:"bytes,11,opt,name=flag,proto3" json:"flag,omitempty"`
	Capital        string                 `protobuf:"bytes,12,opt,name=capital,proto3" json:"capital,omitempty"`
	Population     int64                  `protobuf:"varint,13,opt,name=population,proto3" json:"population,omitempty"`
	Iso3166Alpha3  string                 `protobuf:"bytes,14,opt,name=iso3166_alpha3,json=iso3166Alpha3,proto3" json:"iso3166_alpha3,omitempty"`
	Iso3166Numeric string                 `protobuf:"bytes,15,opt,name=iso3166_numeric,json=iso3166Numeric,proto3" json:"iso3166_numeric,omitempty"`
	Status         string                 `protobuf:"bytes,16,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,17,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      string                 `protobuf:"bytes,18,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Country) Reset() {
	*x = Country{}
	mi := &file_country_v1_country_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Country) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Country) ProtoMessage() {}

func (x *Country) ProtoReflect() protoreflect.Message {
	mi := &file_country_v1_country_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Country.ProtoReflect.Descriptor instead.
func (*Country) Descriptor() ([]byte, []int) {
	return file_country_v1_country_proto_rawDescGZIP(), []int{14}
}

func (x *Country) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Country) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Country) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Country) GetNameEn() string {
	if x != nil {
		return x.NameEn
	}
	return ""
}

func (x *Country) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *Country) GetSubRegion() string {
	if x != nil {
		return x.SubRegion
	}
	return ""
}

func (x *Country) GetCurrencyCode() string {
	if x != nil {
		return x.CurrencyCode
	}
	return ""
}

func (x *Country) GetCurrencySymbol() string {
	if x != nil {
		return x.CurrencySymbol
	}
	return ""
}

func (x *Country) GetPhoneCode() string {
	if x != nil {
		return x.PhoneCode
	}
	return ""
}

func (x *Country) GetTimeZone() string {
	if x != nil {
		return x.TimeZone
	}
	return ""
}

func (x *Country) GetFlag() string {
	if x != nil {
		return x.Flag
	}
	return ""
}

func (x *Country) GetCapital() string {
	if x != nil {
		return x.Capital
	}
	return ""
}

func (x *Country) GetPopulation() int64 {
	if x != nil {
		return x.Population
	}
	return 0
}

func (x *Country) GetIso3166Alpha3() string {
	if x != nil {
		return x.Iso3166Alpha3
	}
	return ""
}

func (x *Country) GetIso3166Numeric() string {
	if x != nil {
		return x.Iso3166Numeric
	}
	return ""
}

func (x *Country) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Country) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Country) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

var File_country_v1_country_proto protoreflect.FileDescriptor

const file_country_v1_country_proto_rawDesc = "" +
	"\n" +
	"\x18country/v1/country.proto\x12\n" +
	"country.v1\x1a\x1cgoogle/api/annotations.proto\"\xb6\x03\n" +
	"\x14CreateCountryRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x17\n" +
	"\aname_en\x18\x03 \x01(\tR\x06nameEn\x12\x16\n" +
	"\x06region\x18\x04 \x01(\tR\x06region\x12\x1d\n" +
	"\n" +
	"sub_region\x18\x05 \x01(\tR\tsubRegion\x12#\n" +
	"\rcurrency_code\x18\x06 \x01(\tR\fcurrencyCode\x12'\n" +
	"\x0fcurrency_symbol\x18\a \x01(\tR\x0ecurrencySymbol\x12\x1d\n" +
	"\n" +
	"phone_code\x18\b \x01(\tR\tphoneCode\x12\x1b\n" +
	"\ttime_zone\x18\t \x01(\tR\btimeZone\x12\x12\n" +
	"\x04flag\x18\n" +
	" \x01(\tR\x04flag\x12\x18\n" +
	"\acapital\x18\v \x01(\tR\acapital\x12\x1e\n" +
	"\n" +
	"population\x18\f \x01(\x03R\n" +
	"population\x12%\n" +
	"\x0eiso3166_alpha3\x18\r \x01(\tR\riso3166Alpha3\x12'\n" +
	"\x0fiso3166_numeric\x18\x0e \x01(\tR\x0eiso3166Numeric\"F\n" +
	"\x15CreateCountryResponse\x12-\n" +
	"\acountry\x18\x01 \x01(\v2\x13.country.v1.CountryR\acountry\"\xde\x03\n" +
	"\x14UpdateCountryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x17\n" +
	"\aname_en\x18\x04 \x01(\tR\x06nameEn\x12\x16\n" +
	"\x06region\x18\x05 \x01(\tR\x06region\x12\x1d\n" +
	"\n" +
	"sub_region\x18\x06 \x01(\tR\tsubRegion\x12#\n" +
	"\rcurrency_code\x18\a \x01(\tR\fcurrencyCode\x12'\n" +
	"\x0fcurrency_symbol\x18\b \x01(\tR\x0ecurrencySymbol\x12\x1d\n" +
	"\n" +
	"phone_code\x18\t \x01(\tR\tphoneCode\x12\x1b\n" +
	"\ttime_zone\x18\n" +
	" \x01(\tR\btimeZone\x12\x12\n" +
	"\x04flag\x18\v \x01(\tR\x04flag\x12\x18\n" +
	"\acapital\x18\f \x01(\tR\acapital\x12\x1e\n" +
	"\n" +
	"population\x18\r \x01(\x03R\n" +
	"population\x12%\n" +
	"\x0eiso3166_alpha3\x18\x0e \x01(\tR\riso3166Alpha3\x12'\n" +
	"\x0fiso3166_numeric\x18\x0f \x01(\tR\x0eiso3166Numeric\x12\x16\n" +
	"\x06status\x18\x10 \x01(\tR\x06status\"F\n" +
	"\x15UpdateCountryResponse\x12-\n" +
	"\acountry\x18\x01 \x01(\v2\x13.country.v1.CountryR\acountry\"&\n" +
	"\x14DeleteCountryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"1\n" +
	"\x15DeleteCountryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"#\n" +
	"\x11GetCountryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"C\n" +
	"\x12GetCountryResponse\x12-\n" +
	"\acountry\x18\x01 \x01(\v2\x13.country.v1.CountryR\acountry\"-\n" +
	"\x17GetCountryByCodeRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"I\n" +
	"\x18GetCountryByCodeResponse\x12-\n" +
	"\acountry\x18\x01 \x01(\v2\x13.country.v1.CountryR\acountry\"\xa3\x01\n" +
	"\x14ListCountriesRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06search\x18\x03 \x01(\tR\x06search\x12\x16\n" +
	"\x06region\x18\x04 \x01(\tR\x06region\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x12\n" +
	"\x04code\x18\x06 \x01(\tR\x04code\"`\n" +
	"\x15ListCountriesResponse\x121\n" +
	"\tcountries\x18\x01 \x03(\v2\x13.country.v1.CountryR\tcountries\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\".\n" +
	"\x16SearchCountriesRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\"L\n" +
	"\x17SearchCountriesResponse\x121\n" +
	"\tcountries\x18\x01 \x03(\v2\x13.country.v1.CountryR\tcountries\"\x8f\x04\n" +
	"\aCountry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x17\n" +
	"\aname_en\x18\x04 \x01(\tR\x06nameEn\x12\x16\n" +
	"\x06region\x18\x05 \x01(\tR\x06region\x12\x1d\n" +
	"\n" +
	"sub_region\x18\x06 \x01(\tR\tsubRegion\x12#\n" +
	"\rcurrency_code\x18\a \x01(\tR\fcurrencyCode\x12'\n" +
	"\x0fcurrency_symbol\x18\b \x01(\tR\x0ecurrencySymbol\x12\x1d\n" +
	"\n" +
	"phone_code\x18\t \x01(\tR\tphoneCode\x12\x1b\n" +
	"\ttime_zone\x18\n" +
	" \x01(\tR\btimeZone\x12\x12\n" +
	"\x04flag\x18\v \x01(\tR\x04flag\x12\x18\n" +
	"\acapital\x18\f \x01(\tR\acapital\x12\x1e\n" +
	"\n" +
	"population\x18\r \x01(\x03R\n" +
	"population\x12%\n" +
	"\x0eiso3166_alpha3\x18\x0e \x01(\tR\riso3166Alpha3\x12'\n" +
	"\x0fiso3166_numeric\x18\x0f \x01(\tR\x0eiso3166Numeric\x12\x16\n" +
	"\x06status\x18\x10 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x11 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x12 \x01(\tR\tupdatedAt2\xd6\x06\n" +
	"\x0eCountryService\x12r\n" +
	"\rCreateCountry\x12 .country.v1.CreateCountryRequest\x1a!.country.v1.CreateCountryResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/api/v1/countries\x12w\n" +
	"\rUpdateCountry\x12 .country.v1.UpdateCountryRequest\x1a!.country.v1.UpdateCountryResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\x1a\x16/api/v1/countries/{id}\x12t\n" +
	"\rDeleteCountry\x12 .country.v1.DeleteCountryRequest\x1a!.country.v1.DeleteCountryResponse\"\x1e\x82\xd3\xe4\x93\x02\x18*\x16/api/v1/countries/{id}\x12k\n" +
	"\n" +
	"GetCountry\x12\x1d.country.v1.GetCountryRequest\x1a\x1e.country.v1.GetCountryResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/api/v1/countries/{id}\x12\x84\x01\n" +
	"\x10GetCountryByCode\x12#.country.v1.GetCountryByCodeRequest\x1a$.country.v1.GetCountryByCodeResponse\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/api/v1/countries/code/{code}\x12o\n" +
	"\rListCountries\x12 .country.v1.ListCountriesRequest\x1a!.country.v1.ListCountriesResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/api/v1/countries\x12|\n" +
	"\x0fSearchCountries\x12\".country.v1.SearchCountriesRequest\x1a#.country.v1.SearchCountriesResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/api/v1/countries/searchB6Z4github.com/go-kratos/kratos-layout/api/country/v1;v1b\x06proto3"

var (
	file_country_v1_country_proto_rawDescOnce sync.Once
	file_country_v1_country_proto_rawDescData []byte
)

func file_country_v1_country_proto_rawDescGZIP() []byte {
	file_country_v1_country_proto_rawDescOnce.Do(func() {
		file_country_v1_country_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_country_v1_country_proto_rawDesc), len(file_country_v1_country_proto_rawDesc)))
	})
	return file_country_v1_country_proto_rawDescData
}

var file_country_v1_country_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_country_v1_country_proto_goTypes = []any{
	(*CreateCountryRequest)(nil),     // 0: country.v1.CreateCountryRequest
	(*CreateCountryResponse)(nil),    // 1: country.v1.CreateCountryResponse
	(*UpdateCountryRequest)(nil),     // 2: country.v1.UpdateCountryRequest
	(*UpdateCountryResponse)(nil),    // 3: country.v1.UpdateCountryResponse
	(*DeleteCountryRequest)(nil),     // 4: country.v1.DeleteCountryRequest
	(*DeleteCountryResponse)(nil),    // 5: country.v1.DeleteCountryResponse
	(*GetCountryRequest)(nil),        // 6: country.v1.GetCountryRequest
	(*GetCountryResponse)(nil),       // 7: country.v1.GetCountryResponse
	(*GetCountryByCodeRequest)(nil),  // 8: country.v1.GetCountryByCodeRequest
	(*GetCountryByCodeResponse)(nil), // 9: country.v1.GetCountryByCodeResponse
	(*ListCountriesRequest)(nil),     // 10: country.v1.ListCountriesRequest
	(*ListCountriesResponse)(nil),    // 11: country.v1.ListCountriesResponse
	(*SearchCountriesRequest)(nil),   // 12: country.v1.SearchCountriesRequest
	(*SearchCountriesResponse)(nil),  // 13: country.v1.SearchCountriesResponse
	(*Country)(nil),                  // 14: country.v1.Country
}
var file_country_v1_country_proto_depIdxs = []int32{
	14, // 0: country.v1.CreateCountryResponse.country:type_name -> country.v1.Country
	14, // 1: country.v1.UpdateCountryResponse.country:type_name -> country.v1.Country
	14, // 2: country.v1.GetCountryResponse.country:type_name -> country.v1.Country
	14, // 3: country.v1.GetCountryByCodeResponse.country:type_name -> country.v1.Country
	14, // 4: country.v1.ListCountriesResponse.countries:type_name -> country.v1.Country
	14, // 5: country.v1.SearchCountriesResponse.countries:type_name -> country.v1.Country
	0,  // 6: country.v1.CountryService.CreateCountry:input_type -> country.v1.CreateCountryRequest
	2,  // 7: country.v1.CountryService.UpdateCountry:input_type -> country.v1.UpdateCountryRequest
	4,  // 8: country.v1.CountryService.DeleteCountry:input_type -> country.v1.DeleteCountryRequest
	6,  // 9: country.v1.CountryService.GetCountry:input_type -> country.v1.GetCountryRequest
	8,  // 10: country.v1.CountryService.GetCountryByCode:input_type -> country.v1.GetCountryByCodeRequest
	10, // 11: country.v1.CountryService.ListCountries:input_type -> country.v1.ListCountriesRequest
	12, // 12: country.v1.CountryService.SearchCountries:input_type -> country.v1.SearchCountriesRequest
	1,  // 13: country.v1.CountryService.CreateCountry:output_type -> country.v1.CreateCountryResponse
	3,  // 14: country.v1.CountryService.UpdateCountry:output_type -> country.v1.UpdateCountryResponse
	5,  // 15: country.v1.CountryService.DeleteCountry:output_type -> country.v1.DeleteCountryResponse
	7,  // 16: country.v1.CountryService.GetCountry:output_type -> country.v1.GetCountryResponse
	9,  // 17: country.v1.CountryService.GetCountryByCode:output_type -> country.v1.GetCountryByCodeResponse
	11, // 18: country.v1.CountryService.ListCountries:output_type -> country.v1.ListCountriesResponse
	13, // 19: country.v1.CountryService.SearchCountries:output_type -> country.v1.SearchCountriesResponse
	13, // [13:20] is the sub-list for method output_type
	6,  // [6:13] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_country_v1_country_proto_init() }
func file_country_v1_country_proto_init() {
	if File_country_v1_country_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_country_v1_country_proto_rawDesc), len(file_country_v1_country_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_country_v1_country_proto_goTypes,
		DependencyIndexes: file_country_v1_country_proto_depIdxs,
		MessageInfos:      file_country_v1_country_proto_msgTypes,
	}.Build()
	File_country_v1_country_proto = out.File
	file_country_v1_country_proto_goTypes = nil
	file_country_v1_country_proto_depIdxs = nil
}
