// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.0
// - protoc             v6.33.1
// source: country/v1/country.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationCountryServiceCreateCountry = "/country.v1.CountryService/CreateCountry"
const OperationCountryServiceDeleteCountry = "/country.v1.CountryService/DeleteCountry"
const OperationCountryServiceGetCountry = "/country.v1.CountryService/GetCountry"
const OperationCountryServiceGetCountryByCode = "/country.v1.CountryService/GetCountryByCode"
const OperationCountryServiceListCountries = "/country.v1.CountryService/ListCountries"
const OperationCountryServiceSearchCountries = "/country.v1.CountryService/SearchCountries"
const OperationCountryServiceUpdateCountry = "/country.v1.CountryService/UpdateCountry"

type CountryServiceHTTPServer interface {
	// CreateCountry Commands
	CreateCountry(context.Context, *CreateCountryRequest) (*CreateCountryResponse, error)
	DeleteCountry(context.Context, *DeleteCountryRequest) (*DeleteCountryResponse, error)
	// GetCountry Queries
	GetCountry(context.Context, *GetCountryRequest) (*GetCountryResponse, error)
	GetCountryByCode(context.Context, *GetCountryByCodeRequest) (*GetCountryByCodeResponse, error)
	ListCountries(context.Context, *ListCountriesRequest) (*ListCountriesResponse, error)
	SearchCountries(context.Context, *SearchCountriesRequest) (*SearchCountriesResponse, error)
	UpdateCountry(context.Context, *UpdateCountryRequest) (*UpdateCountryResponse, error)
}

func RegisterCountryServiceHTTPServer(s *http.Server, srv CountryServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/api/v1/countries", _CountryService_CreateCountry0_HTTP_Handler(srv))
	r.PUT("/api/v1/countries/{id}", _CountryService_UpdateCountry0_HTTP_Handler(srv))
	r.DELETE("/api/v1/countries/{id}", _CountryService_DeleteCountry0_HTTP_Handler(srv))
	r.GET("/api/v1/countries/{id}", _CountryService_GetCountry0_HTTP_Handler(srv))
	r.GET("/api/v1/countries/code/{code}", _CountryService_GetCountryByCode0_HTTP_Handler(srv))
	r.GET("/api/v1/countries", _CountryService_ListCountries0_HTTP_Handler(srv))
	r.GET("/api/v1/countries/search", _CountryService_SearchCountries0_HTTP_Handler(srv))
}

func _CountryService_CreateCountry0_HTTP_Handler(srv CountryServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateCountryRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCountryServiceCreateCountry)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateCountry(ctx, req.(*CreateCountryRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateCountryResponse)
		return ctx.Result(200, reply)
	}
}

func _CountryService_UpdateCountry0_HTTP_Handler(srv CountryServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateCountryRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCountryServiceUpdateCountry)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateCountry(ctx, req.(*UpdateCountryRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateCountryResponse)
		return ctx.Result(200, reply)
	}
}

func _CountryService_DeleteCountry0_HTTP_Handler(srv CountryServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteCountryRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCountryServiceDeleteCountry)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteCountry(ctx, req.(*DeleteCountryRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteCountryResponse)
		return ctx.Result(200, reply)
	}
}

func _CountryService_GetCountry0_HTTP_Handler(srv CountryServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetCountryRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCountryServiceGetCountry)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetCountry(ctx, req.(*GetCountryRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetCountryResponse)
		return ctx.Result(200, reply)
	}
}

func _CountryService_GetCountryByCode0_HTTP_Handler(srv CountryServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetCountryByCodeRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCountryServiceGetCountryByCode)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetCountryByCode(ctx, req.(*GetCountryByCodeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetCountryByCodeResponse)
		return ctx.Result(200, reply)
	}
}

func _CountryService_ListCountries0_HTTP_Handler(srv CountryServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListCountriesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCountryServiceListCountries)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListCountries(ctx, req.(*ListCountriesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListCountriesResponse)
		return ctx.Result(200, reply)
	}
}

func _CountryService_SearchCountries0_HTTP_Handler(srv CountryServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SearchCountriesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCountryServiceSearchCountries)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SearchCountries(ctx, req.(*SearchCountriesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SearchCountriesResponse)
		return ctx.Result(200, reply)
	}
}

type CountryServiceHTTPClient interface {
	// CreateCountry Commands
	CreateCountry(ctx context.Context, req *CreateCountryRequest, opts ...http.CallOption) (rsp *CreateCountryResponse, err error)
	DeleteCountry(ctx context.Context, req *DeleteCountryRequest, opts ...http.CallOption) (rsp *DeleteCountryResponse, err error)
	// GetCountry Queries
	GetCountry(ctx context.Context, req *GetCountryRequest, opts ...http.CallOption) (rsp *GetCountryResponse, err error)
	GetCountryByCode(ctx context.Context, req *GetCountryByCodeRequest, opts ...http.CallOption) (rsp *GetCountryByCodeResponse, err error)
	ListCountries(ctx context.Context, req *ListCountriesRequest, opts ...http.CallOption) (rsp *ListCountriesResponse, err error)
	SearchCountries(ctx context.Context, req *SearchCountriesRequest, opts ...http.CallOption) (rsp *SearchCountriesResponse, err error)
	UpdateCountry(ctx context.Context, req *UpdateCountryRequest, opts ...http.CallOption) (rsp *UpdateCountryResponse, err error)
}

type CountryServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewCountryServiceHTTPClient(client *http.Client) CountryServiceHTTPClient {
	return &CountryServiceHTTPClientImpl{client}
}

// CreateCountry Commands
func (c *CountryServiceHTTPClientImpl) CreateCountry(ctx context.Context, in *CreateCountryRequest, opts ...http.CallOption) (*CreateCountryResponse, error) {
	var out CreateCountryResponse
	pattern := "/api/v1/countries"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationCountryServiceCreateCountry))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CountryServiceHTTPClientImpl) DeleteCountry(ctx context.Context, in *DeleteCountryRequest, opts ...http.CallOption) (*DeleteCountryResponse, error) {
	var out DeleteCountryResponse
	pattern := "/api/v1/countries/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationCountryServiceDeleteCountry))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetCountry Queries
func (c *CountryServiceHTTPClientImpl) GetCountry(ctx context.Context, in *GetCountryRequest, opts ...http.CallOption) (*GetCountryResponse, error) {
	var out GetCountryResponse
	pattern := "/api/v1/countries/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationCountryServiceGetCountry))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CountryServiceHTTPClientImpl) GetCountryByCode(ctx context.Context, in *GetCountryByCodeRequest, opts ...http.CallOption) (*GetCountryByCodeResponse, error) {
	var out GetCountryByCodeResponse
	pattern := "/api/v1/countries/code/{code}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationCountryServiceGetCountryByCode))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CountryServiceHTTPClientImpl) ListCountries(ctx context.Context, in *ListCountriesRequest, opts ...http.CallOption) (*ListCountriesResponse, error) {
	var out ListCountriesResponse
	pattern := "/api/v1/countries"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationCountryServiceListCountries))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CountryServiceHTTPClientImpl) SearchCountries(ctx context.Context, in *SearchCountriesRequest, opts ...http.CallOption) (*SearchCountriesResponse, error) {
	var out SearchCountriesResponse
	pattern := "/api/v1/countries/search"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationCountryServiceSearchCountries))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CountryServiceHTTPClientImpl) UpdateCountry(ctx context.Context, in *UpdateCountryRequest, opts ...http.CallOption) (*UpdateCountryResponse, error) {
	var out UpdateCountryResponse
	pattern := "/api/v1/countries/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationCountryServiceUpdateCountry))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
