// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: ward/v1/error_reason.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorReason int32

const (
	ErrorReason_WARD_UNSPECIFIED    ErrorReason = 0
	ErrorReason_WARD_NOT_FOUND      ErrorReason = 1
	ErrorReason_WARD_ALREADY_EXISTS ErrorReason = 2
	ErrorReason_INVALID_WARD_CODE   ErrorReason = 3
	ErrorReason_PROVINCE_REQUIRED   ErrorReason = 4
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0: "WARD_UNSPECIFIED",
		1: "WARD_NOT_FOUND",
		2: "WARD_ALREADY_EXISTS",
		3: "INVALID_WARD_CODE",
		4: "PROVINCE_REQUIRED",
	}
	ErrorReason_value = map[string]int32{
		"WARD_UNSPECIFIED":    0,
		"WARD_NOT_FOUND":      1,
		"WARD_ALREADY_EXISTS": 2,
		"INVALID_WARD_CODE":   3,
		"PROVINCE_REQUIRED":   4,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_ward_v1_error_reason_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_ward_v1_error_reason_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_ward_v1_error_reason_proto_rawDescGZIP(), []int{0}
}

var File_ward_v1_error_reason_proto protoreflect.FileDescriptor

const file_ward_v1_error_reason_proto_rawDesc = "" +
	"\n" +
	"\x1award/v1/error_reason.proto\x12\award.v1*~\n" +
	"\vErrorReason\x12\x14\n" +
	"\x10WARD_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eWARD_NOT_FOUND\x10\x01\x12\x17\n" +
	"\x13WARD_ALREADY_EXISTS\x10\x02\x12\x15\n" +
	"\x11INVALID_WARD_CODE\x10\x03\x12\x15\n" +
	"\x11PROVINCE_REQUIRED\x10\x04B3Z1github.com/go-kratos/kratos-layout/api/ward/v1;v1b\x06proto3"

var (
	file_ward_v1_error_reason_proto_rawDescOnce sync.Once
	file_ward_v1_error_reason_proto_rawDescData []byte
)

func file_ward_v1_error_reason_proto_rawDescGZIP() []byte {
	file_ward_v1_error_reason_proto_rawDescOnce.Do(func() {
		file_ward_v1_error_reason_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ward_v1_error_reason_proto_rawDesc), len(file_ward_v1_error_reason_proto_rawDesc)))
	})
	return file_ward_v1_error_reason_proto_rawDescData
}

var file_ward_v1_error_reason_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ward_v1_error_reason_proto_goTypes = []any{
	(ErrorReason)(0), // 0: ward.v1.ErrorReason
}
var file_ward_v1_error_reason_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ward_v1_error_reason_proto_init() }
func file_ward_v1_error_reason_proto_init() {
	if File_ward_v1_error_reason_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ward_v1_error_reason_proto_rawDesc), len(file_ward_v1_error_reason_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ward_v1_error_reason_proto_goTypes,
		DependencyIndexes: file_ward_v1_error_reason_proto_depIdxs,
		EnumInfos:         file_ward_v1_error_reason_proto_enumTypes,
	}.Build()
	File_ward_v1_error_reason_proto = out.File
	file_ward_v1_error_reason_proto_goTypes = nil
	file_ward_v1_error_reason_proto_depIdxs = nil
}
