// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.0
// - protoc             v6.33.1
// source: ward/v1/ward.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationWardServiceCreateWard = "/ward.v1.WardService/CreateWard"
const OperationWardServiceDeleteWard = "/ward.v1.WardService/DeleteWard"
const OperationWardServiceGetWard = "/ward.v1.WardService/GetWard"
const OperationWardServiceGetWardByCode = "/ward.v1.WardService/GetWardByCode"
const OperationWardServiceListWards = "/ward.v1.WardService/ListWards"
const OperationWardServiceListWardsByProvince = "/ward.v1.WardService/ListWardsByProvince"
const OperationWardServiceUpdateWard = "/ward.v1.WardService/UpdateWard"

type WardServiceHTTPServer interface {
	// CreateWard Commands
	CreateWard(context.Context, *CreateWardRequest) (*CreateWardResponse, error)
	DeleteWard(context.Context, *DeleteWardRequest) (*DeleteWardResponse, error)
	// GetWard Queries
	GetWard(context.Context, *GetWardRequest) (*GetWardResponse, error)
	GetWardByCode(context.Context, *GetWardByCodeRequest) (*GetWardByCodeResponse, error)
	ListWards(context.Context, *ListWardsRequest) (*ListWardsResponse, error)
	ListWardsByProvince(context.Context, *ListWardsByProvinceRequest) (*ListWardsByProvinceResponse, error)
	UpdateWard(context.Context, *UpdateWardRequest) (*UpdateWardResponse, error)
}

func RegisterWardServiceHTTPServer(s *http.Server, srv WardServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/api/v1/wards", _WardService_CreateWard0_HTTP_Handler(srv))
	r.PUT("/api/v1/wards/{id}", _WardService_UpdateWard0_HTTP_Handler(srv))
	r.DELETE("/api/v1/wards/{id}", _WardService_DeleteWard0_HTTP_Handler(srv))
	r.GET("/api/v1/wards/{id}", _WardService_GetWard0_HTTP_Handler(srv))
	r.GET("/api/v1/wards/code/{code}", _WardService_GetWardByCode0_HTTP_Handler(srv))
	r.GET("/api/v1/wards", _WardService_ListWards0_HTTP_Handler(srv))
	r.GET("/api/v1/provinces/{province_id}/wards", _WardService_ListWardsByProvince0_HTTP_Handler(srv))
}

func _WardService_CreateWard0_HTTP_Handler(srv WardServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateWardRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationWardServiceCreateWard)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateWard(ctx, req.(*CreateWardRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateWardResponse)
		return ctx.Result(200, reply)
	}
}

func _WardService_UpdateWard0_HTTP_Handler(srv WardServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateWardRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationWardServiceUpdateWard)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateWard(ctx, req.(*UpdateWardRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateWardResponse)
		return ctx.Result(200, reply)
	}
}

func _WardService_DeleteWard0_HTTP_Handler(srv WardServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteWardRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationWardServiceDeleteWard)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteWard(ctx, req.(*DeleteWardRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteWardResponse)
		return ctx.Result(200, reply)
	}
}

func _WardService_GetWard0_HTTP_Handler(srv WardServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetWardRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationWardServiceGetWard)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetWard(ctx, req.(*GetWardRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetWardResponse)
		return ctx.Result(200, reply)
	}
}

func _WardService_GetWardByCode0_HTTP_Handler(srv WardServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetWardByCodeRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationWardServiceGetWardByCode)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetWardByCode(ctx, req.(*GetWardByCodeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetWardByCodeResponse)
		return ctx.Result(200, reply)
	}
}

func _WardService_ListWards0_HTTP_Handler(srv WardServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListWardsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationWardServiceListWards)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListWards(ctx, req.(*ListWardsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListWardsResponse)
		return ctx.Result(200, reply)
	}
}

func _WardService_ListWardsByProvince0_HTTP_Handler(srv WardServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListWardsByProvinceRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationWardServiceListWardsByProvince)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListWardsByProvince(ctx, req.(*ListWardsByProvinceRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListWardsByProvinceResponse)
		return ctx.Result(200, reply)
	}
}

type WardServiceHTTPClient interface {
	// CreateWard Commands
	CreateWard(ctx context.Context, req *CreateWardRequest, opts ...http.CallOption) (rsp *CreateWardResponse, err error)
	DeleteWard(ctx context.Context, req *DeleteWardRequest, opts ...http.CallOption) (rsp *DeleteWardResponse, err error)
	// GetWard Queries
	GetWard(ctx context.Context, req *GetWardRequest, opts ...http.CallOption) (rsp *GetWardResponse, err error)
	GetWardByCode(ctx context.Context, req *GetWardByCodeRequest, opts ...http.CallOption) (rsp *GetWardByCodeResponse, err error)
	ListWards(ctx context.Context, req *ListWardsRequest, opts ...http.CallOption) (rsp *ListWardsResponse, err error)
	ListWardsByProvince(ctx context.Context, req *ListWardsByProvinceRequest, opts ...http.CallOption) (rsp *ListWardsByProvinceResponse, err error)
	UpdateWard(ctx context.Context, req *UpdateWardRequest, opts ...http.CallOption) (rsp *UpdateWardResponse, err error)
}

type WardServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewWardServiceHTTPClient(client *http.Client) WardServiceHTTPClient {
	return &WardServiceHTTPClientImpl{client}
}

// CreateWard Commands
func (c *WardServiceHTTPClientImpl) CreateWard(ctx context.Context, in *CreateWardRequest, opts ...http.CallOption) (*CreateWardResponse, error) {
	var out CreateWardResponse
	pattern := "/api/v1/wards"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationWardServiceCreateWard))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *WardServiceHTTPClientImpl) DeleteWard(ctx context.Context, in *DeleteWardRequest, opts ...http.CallOption) (*DeleteWardResponse, error) {
	var out DeleteWardResponse
	pattern := "/api/v1/wards/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationWardServiceDeleteWard))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetWard Queries
func (c *WardServiceHTTPClientImpl) GetWard(ctx context.Context, in *GetWardRequest, opts ...http.CallOption) (*GetWardResponse, error) {
	var out GetWardResponse
	pattern := "/api/v1/wards/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationWardServiceGetWard))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *WardServiceHTTPClientImpl) GetWardByCode(ctx context.Context, in *GetWardByCodeRequest, opts ...http.CallOption) (*GetWardByCodeResponse, error) {
	var out GetWardByCodeResponse
	pattern := "/api/v1/wards/code/{code}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationWardServiceGetWardByCode))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *WardServiceHTTPClientImpl) ListWards(ctx context.Context, in *ListWardsRequest, opts ...http.CallOption) (*ListWardsResponse, error) {
	var out ListWardsResponse
	pattern := "/api/v1/wards"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationWardServiceListWards))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *WardServiceHTTPClientImpl) ListWardsByProvince(ctx context.Context, in *ListWardsByProvinceRequest, opts ...http.CallOption) (*ListWardsByProvinceResponse, error) {
	var out ListWardsByProvinceResponse
	pattern := "/api/v1/provinces/{province_id}/wards"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationWardServiceListWardsByProvince))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *WardServiceHTTPClientImpl) UpdateWard(ctx context.Context, in *UpdateWardRequest, opts ...http.CallOption) (*UpdateWardResponse, error) {
	var out UpdateWardResponse
	pattern := "/api/v1/wards/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationWardServiceUpdateWard))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
