// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: ward/v1/ward.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request/Response messages
type CreateWardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProvinceId    string                 `protobuf:"bytes,1,opt,name=province_id,json=provinceId,proto3" json:"province_id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	NameEn        string                 `protobuf:"bytes,4,opt,name=name_en,json=nameEn,proto3" json:"name_en,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Area          float64                `protobuf:"fixed64,6,opt,name=area,proto3" json:"area,omitempty"`
	Population    int64                  `protobuf:"varint,7,opt,name=population,proto3" json:"population,omitempty"`
	Coordinates   string                 `protobuf:"bytes,8,opt,name=coordinates,proto3" json:"coordinates,omitempty"`
	PostalCode    string                 `protobuf:"bytes,9,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	Address       string                 `protobuf:"bytes,10,opt,name=address,proto3" json:"address,omitempty"`
	SortOrder     int32                  `protobuf:"varint,11,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWardRequest) Reset() {
	*x = CreateWardRequest{}
	mi := &file_ward_v1_ward_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWardRequest) ProtoMessage() {}

func (x *CreateWardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ward_v1_ward_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWardRequest.ProtoReflect.Descriptor instead.
func (*CreateWardRequest) Descriptor() ([]byte, []int) {
	return file_ward_v1_ward_proto_rawDescGZIP(), []int{0}
}

func (x *CreateWardRequest) GetProvinceId() string {
	if x != nil {
		return x.ProvinceId
	}
	return ""
}

func (x *CreateWardRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CreateWardRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateWardRequest) GetNameEn() string {
	if x != nil {
		return x.NameEn
	}
	return ""
}

func (x *CreateWardRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateWardRequest) GetArea() float64 {
	if x != nil {
		return x.Area
	}
	return 0
}

func (x *CreateWardRequest) GetPopulation() int64 {
	if x != nil {
		return x.Population
	}
	return 0
}

func (x *CreateWardRequest) GetCoordinates() string {
	if x != nil {
		return x.Coordinates
	}
	return ""
}

func (x *CreateWardRequest) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

func (x *CreateWardRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CreateWardRequest) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

type CreateWardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ward          *Ward                  `protobuf:"bytes,1,opt,name=ward,proto3" json:"ward,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWardResponse) Reset() {
	*x = CreateWardResponse{}
	mi := &file_ward_v1_ward_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWardResponse) ProtoMessage() {}

func (x *CreateWardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ward_v1_ward_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWardResponse.ProtoReflect.Descriptor instead.
func (*CreateWardResponse) Descriptor() ([]byte, []int) {
	return file_ward_v1_ward_proto_rawDescGZIP(), []int{1}
}

func (x *CreateWardResponse) GetWard() *Ward {
	if x != nil {
		return x.Ward
	}
	return nil
}

type UpdateWardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProvinceId    string                 `protobuf:"bytes,2,opt,name=province_id,json=provinceId,proto3" json:"province_id,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	NameEn        string                 `protobuf:"bytes,5,opt,name=name_en,json=nameEn,proto3" json:"name_en,omitempty"`
	Type          string                 `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	Area          float64                `protobuf:"fixed64,7,opt,name=area,proto3" json:"area,omitempty"`
	Population    int64                  `protobuf:"varint,8,opt,name=population,proto3" json:"population,omitempty"`
	Coordinates   string                 `protobuf:"bytes,9,opt,name=coordinates,proto3" json:"coordinates,omitempty"`
	PostalCode    string                 `protobuf:"bytes,10,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	Address       string                 `protobuf:"bytes,11,opt,name=address,proto3" json:"address,omitempty"`
	SortOrder     int32                  `protobuf:"varint,12,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	Status        string                 `protobuf:"bytes,13,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWardRequest) Reset() {
	*x = UpdateWardRequest{}
	mi := &file_ward_v1_ward_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWardRequest) ProtoMessage() {}

func (x *UpdateWardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ward_v1_ward_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWardRequest.ProtoReflect.Descriptor instead.
func (*UpdateWardRequest) Descriptor() ([]byte, []int) {
	return file_ward_v1_ward_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateWardRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateWardRequest) GetProvinceId() string {
	if x != nil {
		return x.ProvinceId
	}
	return ""
}

func (x *UpdateWardRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *UpdateWardRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateWardRequest) GetNameEn() string {
	if x != nil {
		return x.NameEn
	}
	return ""
}

func (x *UpdateWardRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *UpdateWardRequest) GetArea() float64 {
	if x != nil {
		return x.Area
	}
	return 0
}

func (x *UpdateWardRequest) GetPopulation() int64 {
	if x != nil {
		return x.Population
	}
	return 0
}

func (x *UpdateWardRequest) GetCoordinates() string {
	if x != nil {
		return x.Coordinates
	}
	return ""
}

func (x *UpdateWardRequest) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

func (x *UpdateWardRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *UpdateWardRequest) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *UpdateWardRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UpdateWardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ward          *Ward                  `protobuf:"bytes,1,opt,name=ward,proto3" json:"ward,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWardResponse) Reset() {
	*x = UpdateWardResponse{}
	mi := &file_ward_v1_ward_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWardResponse) ProtoMessage() {}

func (x *UpdateWardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ward_v1_ward_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWardResponse.ProtoReflect.Descriptor instead.
func (*UpdateWardResponse) Descriptor() ([]byte, []int) {
	return file_ward_v1_ward_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateWardResponse) GetWard() *Ward {
	if x != nil {
		return x.Ward
	}
	return nil
}

type DeleteWardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWardRequest) Reset() {
	*x = DeleteWardRequest{}
	mi := &file_ward_v1_ward_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWardRequest) ProtoMessage() {}

func (x *DeleteWardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ward_v1_ward_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWardRequest.ProtoReflect.Descriptor instead.
func (*DeleteWardRequest) Descriptor() ([]byte, []int) {
	return file_ward_v1_ward_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteWardRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteWardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWardResponse) Reset() {
	*x = DeleteWardResponse{}
	mi := &file_ward_v1_ward_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWardResponse) ProtoMessage() {}

func (x *DeleteWardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ward_v1_ward_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWardResponse.ProtoReflect.Descriptor instead.
func (*DeleteWardResponse) Descriptor() ([]byte, []int) {
	return file_ward_v1_ward_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteWardResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetWardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWardRequest) Reset() {
	*x = GetWardRequest{}
	mi := &file_ward_v1_ward_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWardRequest) ProtoMessage() {}

func (x *GetWardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ward_v1_ward_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWardRequest.ProtoReflect.Descriptor instead.
func (*GetWardRequest) Descriptor() ([]byte, []int) {
	return file_ward_v1_ward_proto_rawDescGZIP(), []int{6}
}

func (x *GetWardRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetWardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ward          *Ward                  `protobuf:"bytes,1,opt,name=ward,proto3" json:"ward,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWardResponse) Reset() {
	*x = GetWardResponse{}
	mi := &file_ward_v1_ward_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWardResponse) ProtoMessage() {}

func (x *GetWardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ward_v1_ward_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWardResponse.ProtoReflect.Descriptor instead.
func (*GetWardResponse) Descriptor() ([]byte, []int) {
	return file_ward_v1_ward_proto_rawDescGZIP(), []int{7}
}

func (x *GetWardResponse) GetWard() *Ward {
	if x != nil {
		return x.Ward
	}
	return nil
}

type GetWardByCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	ProvinceId    string                 `protobuf:"bytes,2,opt,name=province_id,json=provinceId,proto3" json:"province_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWardByCodeRequest) Reset() {
	*x = GetWardByCodeRequest{}
	mi := &file_ward_v1_ward_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWardByCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWardByCodeRequest) ProtoMessage() {}

func (x *GetWardByCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ward_v1_ward_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWardByCodeRequest.ProtoReflect.Descriptor instead.
func (*GetWardByCodeRequest) Descriptor() ([]byte, []int) {
	return file_ward_v1_ward_proto_rawDescGZIP(), []int{8}
}

func (x *GetWardByCodeRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *GetWardByCodeRequest) GetProvinceId() string {
	if x != nil {
		return x.ProvinceId
	}
	return ""
}

type GetWardByCodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ward          *Ward                  `protobuf:"bytes,1,opt,name=ward,proto3" json:"ward,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWardByCodeResponse) Reset() {
	*x = GetWardByCodeResponse{}
	mi := &file_ward_v1_ward_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWardByCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWardByCodeResponse) ProtoMessage() {}

func (x *GetWardByCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ward_v1_ward_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWardByCodeResponse.ProtoReflect.Descriptor instead.
func (*GetWardByCodeResponse) Descriptor() ([]byte, []int) {
	return file_ward_v1_ward_proto_rawDescGZIP(), []int{9}
}

func (x *GetWardByCodeResponse) GetWard() *Ward {
	if x != nil {
		return x.Ward
	}
	return nil
}

type ListWardsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Search        string                 `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	ProvinceId    string                 `protobuf:"bytes,4,opt,name=province_id,json=provinceId,proto3" json:"province_id,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Code          string                 `protobuf:"bytes,7,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWardsRequest) Reset() {
	*x = ListWardsRequest{}
	mi := &file_ward_v1_ward_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWardsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWardsRequest) ProtoMessage() {}

func (x *ListWardsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ward_v1_ward_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWardsRequest.ProtoReflect.Descriptor instead.
func (*ListWardsRequest) Descriptor() ([]byte, []int) {
	return file_ward_v1_ward_proto_rawDescGZIP(), []int{10}
}

func (x *ListWardsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListWardsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListWardsRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *ListWardsRequest) GetProvinceId() string {
	if x != nil {
		return x.ProvinceId
	}
	return ""
}

func (x *ListWardsRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ListWardsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListWardsRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type ListWardsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Wards         []*Ward                `protobuf:"bytes,1,rep,name=wards,proto3" json:"wards,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWardsResponse) Reset() {
	*x = ListWardsResponse{}
	mi := &file_ward_v1_ward_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWardsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWardsResponse) ProtoMessage() {}

func (x *ListWardsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ward_v1_ward_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWardsResponse.ProtoReflect.Descriptor instead.
func (*ListWardsResponse) Descriptor() ([]byte, []int) {
	return file_ward_v1_ward_proto_rawDescGZIP(), []int{11}
}

func (x *ListWardsResponse) GetWards() []*Ward {
	if x != nil {
		return x.Wards
	}
	return nil
}

func (x *ListWardsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ListWardsByProvinceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProvinceId    string                 `protobuf:"bytes,1,opt,name=province_id,json=provinceId,proto3" json:"province_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWardsByProvinceRequest) Reset() {
	*x = ListWardsByProvinceRequest{}
	mi := &file_ward_v1_ward_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWardsByProvinceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWardsByProvinceRequest) ProtoMessage() {}

func (x *ListWardsByProvinceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ward_v1_ward_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWardsByProvinceRequest.ProtoReflect.Descriptor instead.
func (*ListWardsByProvinceRequest) Descriptor() ([]byte, []int) {
	return file_ward_v1_ward_proto_rawDescGZIP(), []int{12}
}

func (x *ListWardsByProvinceRequest) GetProvinceId() string {
	if x != nil {
		return x.ProvinceId
	}
	return ""
}

type ListWardsByProvinceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Wards         []*Ward                `protobuf:"bytes,1,rep,name=wards,proto3" json:"wards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWardsByProvinceResponse) Reset() {
	*x = ListWardsByProvinceResponse{}
	mi := &file_ward_v1_ward_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWardsByProvinceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWardsByProvinceResponse) ProtoMessage() {}

func (x *ListWardsByProvinceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ward_v1_ward_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWardsByProvinceResponse.ProtoReflect.Descriptor instead.
func (*ListWardsByProvinceResponse) Descriptor() ([]byte, []int) {
	return file_ward_v1_ward_proto_rawDescGZIP(), []int{13}
}

func (x *ListWardsByProvinceResponse) GetWards() []*Ward {
	if x != nil {
		return x.Wards
	}
	return nil
}

type Ward struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProvinceId    string                 `protobuf:"bytes,2,opt,name=province_id,json=provinceId,proto3" json:"province_id,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	NameEn        string                 `protobuf:"bytes,5,opt,name=name_en,json=nameEn,proto3" json:"name_en,omitempty"`
	Type          string                 `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	Area          float64                `protobuf:"fixed64,7,opt,name=area,proto3" json:"area,omitempty"`
	Population    int64                  `protobuf:"varint,8,opt,name=population,proto3" json:"population,omitempty"`
	Coordinates   string                 `protobuf:"bytes,9,opt,name=coordinates,proto3" json:"coordinates,omitempty"`
	PostalCode    string                 `protobuf:"bytes,10,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	Address       string                 `protobuf:"bytes,11,opt,name=address,proto3" json:"address,omitempty"`
	SortOrder     int32                  `protobuf:"varint,12,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	Status        string                 `protobuf:"bytes,13,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,15,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,16,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	UpdatedBy     string                 `protobuf:"bytes,17,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ward) Reset() {
	*x = Ward{}
	mi := &file_ward_v1_ward_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ward) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ward) ProtoMessage() {}

func (x *Ward) ProtoReflect() protoreflect.Message {
	mi := &file_ward_v1_ward_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ward.ProtoReflect.Descriptor instead.
func (*Ward) Descriptor() ([]byte, []int) {
	return file_ward_v1_ward_proto_rawDescGZIP(), []int{14}
}

func (x *Ward) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Ward) GetProvinceId() string {
	if x != nil {
		return x.ProvinceId
	}
	return ""
}

func (x *Ward) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Ward) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Ward) GetNameEn() string {
	if x != nil {
		return x.NameEn
	}
	return ""
}

func (x *Ward) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Ward) GetArea() float64 {
	if x != nil {
		return x.Area
	}
	return 0
}

func (x *Ward) GetPopulation() int64 {
	if x != nil {
		return x.Population
	}
	return 0
}

func (x *Ward) GetCoordinates() string {
	if x != nil {
		return x.Coordinates
	}
	return ""
}

func (x *Ward) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

func (x *Ward) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Ward) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *Ward) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Ward) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Ward) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Ward) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *Ward) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

var File_ward_v1_ward_proto protoreflect.FileDescriptor

const file_ward_v1_ward_proto_rawDesc = "" +
	"\n" +
	"\x12ward/v1/ward.proto\x12\award.v1\x1a\x1cgoogle/api/annotations.proto\"\xb9\x02\n" +
	"\x11CreateWardRequest\x12\x1f\n" +
	"\vprovince_id\x18\x01 \x01(\tR\n" +
	"provinceId\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x17\n" +
	"\aname_en\x18\x04 \x01(\tR\x06nameEn\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\x12\n" +
	"\x04area\x18\x06 \x01(\x01R\x04area\x12\x1e\n" +
	"\n" +
	"population\x18\a \x01(\x03R\n" +
	"population\x12 \n" +
	"\vcoordinates\x18\b \x01(\tR\vcoordinates\x12\x1f\n" +
	"\vpostal_code\x18\t \x01(\tR\n" +
	"postalCode\x12\x18\n" +
	"\aaddress\x18\n" +
	" \x01(\tR\aaddress\x12\x1d\n" +
	"\n" +
	"sort_order\x18\v \x01(\x05R\tsortOrder\"7\n" +
	"\x12CreateWardResponse\x12!\n" +
	"\x04ward\x18\x01 \x01(\v2\r.ward.v1.WardR\x04ward\"\xe1\x02\n" +
	"\x11UpdateWardRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vprovince_id\x18\x02 \x01(\tR\n" +
	"provinceId\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x17\n" +
	"\aname_en\x18\x05 \x01(\tR\x06nameEn\x12\x12\n" +
	"\x04type\x18\x06 \x01(\tR\x04type\x12\x12\n" +
	"\x04area\x18\a \x01(\x01R\x04area\x12\x1e\n" +
	"\n" +
	"population\x18\b \x01(\x03R\n" +
	"population\x12 \n" +
	"\vcoordinates\x18\t \x01(\tR\vcoordinates\x12\x1f\n" +
	"\vpostal_code\x18\n" +
	" \x01(\tR\n" +
	"postalCode\x12\x18\n" +
	"\aaddress\x18\v \x01(\tR\aaddress\x12\x1d\n" +
	"\n" +
	"sort_order\x18\f \x01(\x05R\tsortOrder\x12\x16\n" +
	"\x06status\x18\r \x01(\tR\x06status\"7\n" +
	"\x12UpdateWardResponse\x12!\n" +
	"\x04ward\x18\x01 \x01(\v2\r.ward.v1.WardR\x04ward\"#\n" +
	"\x11DeleteWardRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\".\n" +
	"\x12DeleteWardResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\" \n" +
	"\x0eGetWardRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"4\n" +
	"\x0fGetWardResponse\x12!\n" +
	"\x04ward\x18\x01 \x01(\v2\r.ward.v1.WardR\x04ward\"K\n" +
	"\x14GetWardByCodeRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x1f\n" +
	"\vprovince_id\x18\x02 \x01(\tR\n" +
	"provinceId\":\n" +
	"\x15GetWardByCodeResponse\x12!\n" +
	"\x04ward\x18\x01 \x01(\v2\r.ward.v1.WardR\x04ward\"\xbc\x01\n" +
	"\x10ListWardsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06search\x18\x03 \x01(\tR\x06search\x12\x1f\n" +
	"\vprovince_id\x18\x04 \x01(\tR\n" +
	"provinceId\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x12\n" +
	"\x04code\x18\a \x01(\tR\x04code\"N\n" +
	"\x11ListWardsResponse\x12#\n" +
	"\x05wards\x18\x01 \x03(\v2\r.ward.v1.WardR\x05wards\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"=\n" +
	"\x1aListWardsByProvinceRequest\x12\x1f\n" +
	"\vprovince_id\x18\x01 \x01(\tR\n" +
	"provinceId\"B\n" +
	"\x1bListWardsByProvinceResponse\x12#\n" +
	"\x05wards\x18\x01 \x03(\v2\r.ward.v1.WardR\x05wards\"\xd0\x03\n" +
	"\x04Ward\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vprovince_id\x18\x02 \x01(\tR\n" +
	"provinceId\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x17\n" +
	"\aname_en\x18\x05 \x01(\tR\x06nameEn\x12\x12\n" +
	"\x04type\x18\x06 \x01(\tR\x04type\x12\x12\n" +
	"\x04area\x18\a \x01(\x01R\x04area\x12\x1e\n" +
	"\n" +
	"population\x18\b \x01(\x03R\n" +
	"population\x12 \n" +
	"\vcoordinates\x18\t \x01(\tR\vcoordinates\x12\x1f\n" +
	"\vpostal_code\x18\n" +
	" \x01(\tR\n" +
	"postalCode\x12\x18\n" +
	"\aaddress\x18\v \x01(\tR\aaddress\x12\x1d\n" +
	"\n" +
	"sort_order\x18\f \x01(\x05R\tsortOrder\x12\x16\n" +
	"\x06status\x18\r \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x0e \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x0f \x01(\tR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"created_by\x18\x10 \x01(\tR\tcreatedBy\x12\x1d\n" +
	"\n" +
	"updated_by\x18\x11 \x01(\tR\tupdatedBy2\xf1\x05\n" +
	"\vWardService\x12_\n" +
	"\n" +
	"CreateWard\x12\x1a.ward.v1.CreateWardRequest\x1a\x1b.ward.v1.CreateWardResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/api/v1/wards\x12d\n" +
	"\n" +
	"UpdateWard\x12\x1a.ward.v1.UpdateWardRequest\x1a\x1b.ward.v1.UpdateWardResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\x1a\x12/api/v1/wards/{id}\x12a\n" +
	"\n" +
	"DeleteWard\x12\x1a.ward.v1.DeleteWardRequest\x1a\x1b.ward.v1.DeleteWardResponse\"\x1a\x82\xd3\xe4\x93\x02\x14*\x12/api/v1/wards/{id}\x12X\n" +
	"\aGetWard\x12\x17.ward.v1.GetWardRequest\x1a\x18.ward.v1.GetWardResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/api/v1/wards/{id}\x12q\n" +
	"\rGetWardByCode\x12\x1d.ward.v1.GetWardByCodeRequest\x1a\x1e.ward.v1.GetWardByCodeResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/api/v1/wards/code/{code}\x12Y\n" +
	"\tListWards\x12\x19.ward.v1.ListWardsRequest\x1a\x1a.ward.v1.ListWardsResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/api/v1/wards\x12\x8f\x01\n" +
	"\x13ListWardsByProvince\x12#.ward.v1.ListWardsByProvinceRequest\x1a$.ward.v1.ListWardsByProvinceResponse\"-\x82\xd3\xe4\x93\x02'\x12%/api/v1/provinces/{province_id}/wardsB3Z1github.com/go-kratos/kratos-layout/api/ward/v1;v1b\x06proto3"

var (
	file_ward_v1_ward_proto_rawDescOnce sync.Once
	file_ward_v1_ward_proto_rawDescData []byte
)

func file_ward_v1_ward_proto_rawDescGZIP() []byte {
	file_ward_v1_ward_proto_rawDescOnce.Do(func() {
		file_ward_v1_ward_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ward_v1_ward_proto_rawDesc), len(file_ward_v1_ward_proto_rawDesc)))
	})
	return file_ward_v1_ward_proto_rawDescData
}

var file_ward_v1_ward_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_ward_v1_ward_proto_goTypes = []any{
	(*CreateWardRequest)(nil),           // 0: ward.v1.CreateWardRequest
	(*CreateWardResponse)(nil),          // 1: ward.v1.CreateWardResponse
	(*UpdateWardRequest)(nil),           // 2: ward.v1.UpdateWardRequest
	(*UpdateWardResponse)(nil),          // 3: ward.v1.UpdateWardResponse
	(*DeleteWardRequest)(nil),           // 4: ward.v1.DeleteWardRequest
	(*DeleteWardResponse)(nil),          // 5: ward.v1.DeleteWardResponse
	(*GetWardRequest)(nil),              // 6: ward.v1.GetWardRequest
	(*GetWardResponse)(nil),             // 7: ward.v1.GetWardResponse
	(*GetWardByCodeRequest)(nil),        // 8: ward.v1.GetWardByCodeRequest
	(*GetWardByCodeResponse)(nil),       // 9: ward.v1.GetWardByCodeResponse
	(*ListWardsRequest)(nil),            // 10: ward.v1.ListWardsRequest
	(*ListWardsResponse)(nil),           // 11: ward.v1.ListWardsResponse
	(*ListWardsByProvinceRequest)(nil),  // 12: ward.v1.ListWardsByProvinceRequest
	(*ListWardsByProvinceResponse)(nil), // 13: ward.v1.ListWardsByProvinceResponse
	(*Ward)(nil),                        // 14: ward.v1.Ward
}
var file_ward_v1_ward_proto_depIdxs = []int32{
	14, // 0: ward.v1.CreateWardResponse.ward:type_name -> ward.v1.Ward
	14, // 1: ward.v1.UpdateWardResponse.ward:type_name -> ward.v1.Ward
	14, // 2: ward.v1.GetWardResponse.ward:type_name -> ward.v1.Ward
	14, // 3: ward.v1.GetWardByCodeResponse.ward:type_name -> ward.v1.Ward
	14, // 4: ward.v1.ListWardsResponse.wards:type_name -> ward.v1.Ward
	14, // 5: ward.v1.ListWardsByProvinceResponse.wards:type_name -> ward.v1.Ward
	0,  // 6: ward.v1.WardService.CreateWard:input_type -> ward.v1.CreateWardRequest
	2,  // 7: ward.v1.WardService.UpdateWard:input_type -> ward.v1.UpdateWardRequest
	4,  // 8: ward.v1.WardService.DeleteWard:input_type -> ward.v1.DeleteWardRequest
	6,  // 9: ward.v1.WardService.GetWard:input_type -> ward.v1.GetWardRequest
	8,  // 10: ward.v1.WardService.GetWardByCode:input_type -> ward.v1.GetWardByCodeRequest
	10, // 11: ward.v1.WardService.ListWards:input_type -> ward.v1.ListWardsRequest
	12, // 12: ward.v1.WardService.ListWardsByProvince:input_type -> ward.v1.ListWardsByProvinceRequest
	1,  // 13: ward.v1.WardService.CreateWard:output_type -> ward.v1.CreateWardResponse
	3,  // 14: ward.v1.WardService.UpdateWard:output_type -> ward.v1.UpdateWardResponse
	5,  // 15: ward.v1.WardService.DeleteWard:output_type -> ward.v1.DeleteWardResponse
	7,  // 16: ward.v1.WardService.GetWard:output_type -> ward.v1.GetWardResponse
	9,  // 17: ward.v1.WardService.GetWardByCode:output_type -> ward.v1.GetWardByCodeResponse
	11, // 18: ward.v1.WardService.ListWards:output_type -> ward.v1.ListWardsResponse
	13, // 19: ward.v1.WardService.ListWardsByProvince:output_type -> ward.v1.ListWardsByProvinceResponse
	13, // [13:20] is the sub-list for method output_type
	6,  // [6:13] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_ward_v1_ward_proto_init() }
func file_ward_v1_ward_proto_init() {
	if File_ward_v1_ward_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ward_v1_ward_proto_rawDesc), len(file_ward_v1_ward_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ward_v1_ward_proto_goTypes,
		DependencyIndexes: file_ward_v1_ward_proto_depIdxs,
		MessageInfos:      file_ward_v1_ward_proto_msgTypes,
	}.Build()
	File_ward_v1_ward_proto = out.File
	file_ward_v1_ward_proto_goTypes = nil
	file_ward_v1_ward_proto_depIdxs = nil
}
