// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: province/v1/province.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProvinceService_CreateProvince_FullMethodName         = "/province.v1.ProvinceService/CreateProvince"
	ProvinceService_UpdateProvince_FullMethodName         = "/province.v1.ProvinceService/UpdateProvince"
	ProvinceService_DeleteProvince_FullMethodName         = "/province.v1.ProvinceService/DeleteProvince"
	ProvinceService_GetProvince_FullMethodName            = "/province.v1.ProvinceService/GetProvince"
	ProvinceService_GetProvinceByCode_FullMethodName      = "/province.v1.ProvinceService/GetProvinceByCode"
	ProvinceService_ListProvinces_FullMethodName          = "/province.v1.ProvinceService/ListProvinces"
	ProvinceService_ListProvincesByCountry_FullMethodName = "/province.v1.ProvinceService/ListProvincesByCountry"
)

// ProvinceServiceClient is the client API for ProvinceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProvinceServiceClient interface {
	// Commands
	CreateProvince(ctx context.Context, in *CreateProvinceRequest, opts ...grpc.CallOption) (*CreateProvinceResponse, error)
	UpdateProvince(ctx context.Context, in *UpdateProvinceRequest, opts ...grpc.CallOption) (*UpdateProvinceResponse, error)
	DeleteProvince(ctx context.Context, in *DeleteProvinceRequest, opts ...grpc.CallOption) (*DeleteProvinceResponse, error)
	// Queries
	GetProvince(ctx context.Context, in *GetProvinceRequest, opts ...grpc.CallOption) (*GetProvinceResponse, error)
	GetProvinceByCode(ctx context.Context, in *GetProvinceByCodeRequest, opts ...grpc.CallOption) (*GetProvinceByCodeResponse, error)
	ListProvinces(ctx context.Context, in *ListProvincesRequest, opts ...grpc.CallOption) (*ListProvincesResponse, error)
	ListProvincesByCountry(ctx context.Context, in *ListProvincesByCountryRequest, opts ...grpc.CallOption) (*ListProvincesByCountryResponse, error)
}

type provinceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProvinceServiceClient(cc grpc.ClientConnInterface) ProvinceServiceClient {
	return &provinceServiceClient{cc}
}

func (c *provinceServiceClient) CreateProvince(ctx context.Context, in *CreateProvinceRequest, opts ...grpc.CallOption) (*CreateProvinceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateProvinceResponse)
	err := c.cc.Invoke(ctx, ProvinceService_CreateProvince_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *provinceServiceClient) UpdateProvince(ctx context.Context, in *UpdateProvinceRequest, opts ...grpc.CallOption) (*UpdateProvinceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateProvinceResponse)
	err := c.cc.Invoke(ctx, ProvinceService_UpdateProvince_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *provinceServiceClient) DeleteProvince(ctx context.Context, in *DeleteProvinceRequest, opts ...grpc.CallOption) (*DeleteProvinceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteProvinceResponse)
	err := c.cc.Invoke(ctx, ProvinceService_DeleteProvince_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *provinceServiceClient) GetProvince(ctx context.Context, in *GetProvinceRequest, opts ...grpc.CallOption) (*GetProvinceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProvinceResponse)
	err := c.cc.Invoke(ctx, ProvinceService_GetProvince_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *provinceServiceClient) GetProvinceByCode(ctx context.Context, in *GetProvinceByCodeRequest, opts ...grpc.CallOption) (*GetProvinceByCodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProvinceByCodeResponse)
	err := c.cc.Invoke(ctx, ProvinceService_GetProvinceByCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *provinceServiceClient) ListProvinces(ctx context.Context, in *ListProvincesRequest, opts ...grpc.CallOption) (*ListProvincesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProvincesResponse)
	err := c.cc.Invoke(ctx, ProvinceService_ListProvinces_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *provinceServiceClient) ListProvincesByCountry(ctx context.Context, in *ListProvincesByCountryRequest, opts ...grpc.CallOption) (*ListProvincesByCountryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProvincesByCountryResponse)
	err := c.cc.Invoke(ctx, ProvinceService_ListProvincesByCountry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProvinceServiceServer is the server API for ProvinceService service.
// All implementations must embed UnimplementedProvinceServiceServer
// for forward compatibility.
type ProvinceServiceServer interface {
	// Commands
	CreateProvince(context.Context, *CreateProvinceRequest) (*CreateProvinceResponse, error)
	UpdateProvince(context.Context, *UpdateProvinceRequest) (*UpdateProvinceResponse, error)
	DeleteProvince(context.Context, *DeleteProvinceRequest) (*DeleteProvinceResponse, error)
	// Queries
	GetProvince(context.Context, *GetProvinceRequest) (*GetProvinceResponse, error)
	GetProvinceByCode(context.Context, *GetProvinceByCodeRequest) (*GetProvinceByCodeResponse, error)
	ListProvinces(context.Context, *ListProvincesRequest) (*ListProvincesResponse, error)
	ListProvincesByCountry(context.Context, *ListProvincesByCountryRequest) (*ListProvincesByCountryResponse, error)
	mustEmbedUnimplementedProvinceServiceServer()
}

// UnimplementedProvinceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProvinceServiceServer struct{}

func (UnimplementedProvinceServiceServer) CreateProvince(context.Context, *CreateProvinceRequest) (*CreateProvinceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProvince not implemented")
}
func (UnimplementedProvinceServiceServer) UpdateProvince(context.Context, *UpdateProvinceRequest) (*UpdateProvinceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProvince not implemented")
}
func (UnimplementedProvinceServiceServer) DeleteProvince(context.Context, *DeleteProvinceRequest) (*DeleteProvinceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteProvince not implemented")
}
func (UnimplementedProvinceServiceServer) GetProvince(context.Context, *GetProvinceRequest) (*GetProvinceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProvince not implemented")
}
func (UnimplementedProvinceServiceServer) GetProvinceByCode(context.Context, *GetProvinceByCodeRequest) (*GetProvinceByCodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProvinceByCode not implemented")
}
func (UnimplementedProvinceServiceServer) ListProvinces(context.Context, *ListProvincesRequest) (*ListProvincesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProvinces not implemented")
}
func (UnimplementedProvinceServiceServer) ListProvincesByCountry(context.Context, *ListProvincesByCountryRequest) (*ListProvincesByCountryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProvincesByCountry not implemented")
}
func (UnimplementedProvinceServiceServer) mustEmbedUnimplementedProvinceServiceServer() {}
func (UnimplementedProvinceServiceServer) testEmbeddedByValue()                         {}

// UnsafeProvinceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProvinceServiceServer will
// result in compilation errors.
type UnsafeProvinceServiceServer interface {
	mustEmbedUnimplementedProvinceServiceServer()
}

func RegisterProvinceServiceServer(s grpc.ServiceRegistrar, srv ProvinceServiceServer) {
	// If the following call pancis, it indicates UnimplementedProvinceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProvinceService_ServiceDesc, srv)
}

func _ProvinceService_CreateProvince_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProvinceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProvinceServiceServer).CreateProvince(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProvinceService_CreateProvince_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProvinceServiceServer).CreateProvince(ctx, req.(*CreateProvinceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProvinceService_UpdateProvince_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProvinceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProvinceServiceServer).UpdateProvince(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProvinceService_UpdateProvince_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProvinceServiceServer).UpdateProvince(ctx, req.(*UpdateProvinceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProvinceService_DeleteProvince_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProvinceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProvinceServiceServer).DeleteProvince(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProvinceService_DeleteProvince_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProvinceServiceServer).DeleteProvince(ctx, req.(*DeleteProvinceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProvinceService_GetProvince_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProvinceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProvinceServiceServer).GetProvince(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProvinceService_GetProvince_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProvinceServiceServer).GetProvince(ctx, req.(*GetProvinceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProvinceService_GetProvinceByCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProvinceByCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProvinceServiceServer).GetProvinceByCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProvinceService_GetProvinceByCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProvinceServiceServer).GetProvinceByCode(ctx, req.(*GetProvinceByCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProvinceService_ListProvinces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProvincesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProvinceServiceServer).ListProvinces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProvinceService_ListProvinces_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProvinceServiceServer).ListProvinces(ctx, req.(*ListProvincesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProvinceService_ListProvincesByCountry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProvincesByCountryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProvinceServiceServer).ListProvincesByCountry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProvinceService_ListProvincesByCountry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProvinceServiceServer).ListProvincesByCountry(ctx, req.(*ListProvincesByCountryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProvinceService_ServiceDesc is the grpc.ServiceDesc for ProvinceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProvinceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "province.v1.ProvinceService",
	HandlerType: (*ProvinceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateProvince",
			Handler:    _ProvinceService_CreateProvince_Handler,
		},
		{
			MethodName: "UpdateProvince",
			Handler:    _ProvinceService_UpdateProvince_Handler,
		},
		{
			MethodName: "DeleteProvince",
			Handler:    _ProvinceService_DeleteProvince_Handler,
		},
		{
			MethodName: "GetProvince",
			Handler:    _ProvinceService_GetProvince_Handler,
		},
		{
			MethodName: "GetProvinceByCode",
			Handler:    _ProvinceService_GetProvinceByCode_Handler,
		},
		{
			MethodName: "ListProvinces",
			Handler:    _ProvinceService_ListProvinces_Handler,
		},
		{
			MethodName: "ListProvincesByCountry",
			Handler:    _ProvinceService_ListProvincesByCountry_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "province/v1/province.proto",
}
