// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: province/v1/province.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request/Response messages
type CreateProvinceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CountryId     string                 `protobuf:"bytes,1,opt,name=country_id,json=countryId,proto3" json:"country_id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	NameEn        string                 `protobuf:"bytes,4,opt,name=name_en,json=nameEn,proto3" json:"name_en,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Area          float64                `protobuf:"fixed64,6,opt,name=area,proto3" json:"area,omitempty"`
	Population    int64                  `protobuf:"varint,7,opt,name=population,proto3" json:"population,omitempty"`
	Coordinates   string                 `protobuf:"bytes,8,opt,name=coordinates,proto3" json:"coordinates,omitempty"`
	Capital       string                 `protobuf:"bytes,9,opt,name=capital,proto3" json:"capital,omitempty"`
	PostalCode    string                 `protobuf:"bytes,10,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	PhonePrefix   string                 `protobuf:"bytes,11,opt,name=phone_prefix,json=phonePrefix,proto3" json:"phone_prefix,omitempty"`
	SortOrder     int32                  `protobuf:"varint,12,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProvinceRequest) Reset() {
	*x = CreateProvinceRequest{}
	mi := &file_province_v1_province_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProvinceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProvinceRequest) ProtoMessage() {}

func (x *CreateProvinceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_province_v1_province_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProvinceRequest.ProtoReflect.Descriptor instead.
func (*CreateProvinceRequest) Descriptor() ([]byte, []int) {
	return file_province_v1_province_proto_rawDescGZIP(), []int{0}
}

func (x *CreateProvinceRequest) GetCountryId() string {
	if x != nil {
		return x.CountryId
	}
	return ""
}

func (x *CreateProvinceRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CreateProvinceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProvinceRequest) GetNameEn() string {
	if x != nil {
		return x.NameEn
	}
	return ""
}

func (x *CreateProvinceRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateProvinceRequest) GetArea() float64 {
	if x != nil {
		return x.Area
	}
	return 0
}

func (x *CreateProvinceRequest) GetPopulation() int64 {
	if x != nil {
		return x.Population
	}
	return 0
}

func (x *CreateProvinceRequest) GetCoordinates() string {
	if x != nil {
		return x.Coordinates
	}
	return ""
}

func (x *CreateProvinceRequest) GetCapital() string {
	if x != nil {
		return x.Capital
	}
	return ""
}

func (x *CreateProvinceRequest) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

func (x *CreateProvinceRequest) GetPhonePrefix() string {
	if x != nil {
		return x.PhonePrefix
	}
	return ""
}

func (x *CreateProvinceRequest) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

type CreateProvinceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Province      *Province              `protobuf:"bytes,1,opt,name=province,proto3" json:"province,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProvinceResponse) Reset() {
	*x = CreateProvinceResponse{}
	mi := &file_province_v1_province_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProvinceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProvinceResponse) ProtoMessage() {}

func (x *CreateProvinceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_province_v1_province_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProvinceResponse.ProtoReflect.Descriptor instead.
func (*CreateProvinceResponse) Descriptor() ([]byte, []int) {
	return file_province_v1_province_proto_rawDescGZIP(), []int{1}
}

func (x *CreateProvinceResponse) GetProvince() *Province {
	if x != nil {
		return x.Province
	}
	return nil
}

type UpdateProvinceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CountryId     string                 `protobuf:"bytes,2,opt,name=country_id,json=countryId,proto3" json:"country_id,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	NameEn        string                 `protobuf:"bytes,5,opt,name=name_en,json=nameEn,proto3" json:"name_en,omitempty"`
	Type          string                 `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	Area          float64                `protobuf:"fixed64,7,opt,name=area,proto3" json:"area,omitempty"`
	Population    int64                  `protobuf:"varint,8,opt,name=population,proto3" json:"population,omitempty"`
	Coordinates   string                 `protobuf:"bytes,9,opt,name=coordinates,proto3" json:"coordinates,omitempty"`
	Capital       string                 `protobuf:"bytes,10,opt,name=capital,proto3" json:"capital,omitempty"`
	PostalCode    string                 `protobuf:"bytes,11,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	PhonePrefix   string                 `protobuf:"bytes,12,opt,name=phone_prefix,json=phonePrefix,proto3" json:"phone_prefix,omitempty"`
	SortOrder     int32                  `protobuf:"varint,13,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	Status        string                 `protobuf:"bytes,14,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProvinceRequest) Reset() {
	*x = UpdateProvinceRequest{}
	mi := &file_province_v1_province_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProvinceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProvinceRequest) ProtoMessage() {}

func (x *UpdateProvinceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_province_v1_province_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProvinceRequest.ProtoReflect.Descriptor instead.
func (*UpdateProvinceRequest) Descriptor() ([]byte, []int) {
	return file_province_v1_province_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateProvinceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateProvinceRequest) GetCountryId() string {
	if x != nil {
		return x.CountryId
	}
	return ""
}

func (x *UpdateProvinceRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *UpdateProvinceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateProvinceRequest) GetNameEn() string {
	if x != nil {
		return x.NameEn
	}
	return ""
}

func (x *UpdateProvinceRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *UpdateProvinceRequest) GetArea() float64 {
	if x != nil {
		return x.Area
	}
	return 0
}

func (x *UpdateProvinceRequest) GetPopulation() int64 {
	if x != nil {
		return x.Population
	}
	return 0
}

func (x *UpdateProvinceRequest) GetCoordinates() string {
	if x != nil {
		return x.Coordinates
	}
	return ""
}

func (x *UpdateProvinceRequest) GetCapital() string {
	if x != nil {
		return x.Capital
	}
	return ""
}

func (x *UpdateProvinceRequest) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

func (x *UpdateProvinceRequest) GetPhonePrefix() string {
	if x != nil {
		return x.PhonePrefix
	}
	return ""
}

func (x *UpdateProvinceRequest) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *UpdateProvinceRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UpdateProvinceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Province      *Province              `protobuf:"bytes,1,opt,name=province,proto3" json:"province,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProvinceResponse) Reset() {
	*x = UpdateProvinceResponse{}
	mi := &file_province_v1_province_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProvinceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProvinceResponse) ProtoMessage() {}

func (x *UpdateProvinceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_province_v1_province_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProvinceResponse.ProtoReflect.Descriptor instead.
func (*UpdateProvinceResponse) Descriptor() ([]byte, []int) {
	return file_province_v1_province_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateProvinceResponse) GetProvince() *Province {
	if x != nil {
		return x.Province
	}
	return nil
}

type DeleteProvinceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProvinceRequest) Reset() {
	*x = DeleteProvinceRequest{}
	mi := &file_province_v1_province_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProvinceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProvinceRequest) ProtoMessage() {}

func (x *DeleteProvinceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_province_v1_province_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProvinceRequest.ProtoReflect.Descriptor instead.
func (*DeleteProvinceRequest) Descriptor() ([]byte, []int) {
	return file_province_v1_province_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteProvinceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteProvinceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProvinceResponse) Reset() {
	*x = DeleteProvinceResponse{}
	mi := &file_province_v1_province_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProvinceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProvinceResponse) ProtoMessage() {}

func (x *DeleteProvinceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_province_v1_province_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProvinceResponse.ProtoReflect.Descriptor instead.
func (*DeleteProvinceResponse) Descriptor() ([]byte, []int) {
	return file_province_v1_province_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteProvinceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetProvinceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProvinceRequest) Reset() {
	*x = GetProvinceRequest{}
	mi := &file_province_v1_province_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProvinceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProvinceRequest) ProtoMessage() {}

func (x *GetProvinceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_province_v1_province_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProvinceRequest.ProtoReflect.Descriptor instead.
func (*GetProvinceRequest) Descriptor() ([]byte, []int) {
	return file_province_v1_province_proto_rawDescGZIP(), []int{6}
}

func (x *GetProvinceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetProvinceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Province      *Province              `protobuf:"bytes,1,opt,name=province,proto3" json:"province,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProvinceResponse) Reset() {
	*x = GetProvinceResponse{}
	mi := &file_province_v1_province_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProvinceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProvinceResponse) ProtoMessage() {}

func (x *GetProvinceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_province_v1_province_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProvinceResponse.ProtoReflect.Descriptor instead.
func (*GetProvinceResponse) Descriptor() ([]byte, []int) {
	return file_province_v1_province_proto_rawDescGZIP(), []int{7}
}

func (x *GetProvinceResponse) GetProvince() *Province {
	if x != nil {
		return x.Province
	}
	return nil
}

type GetProvinceByCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	CountryId     string                 `protobuf:"bytes,2,opt,name=country_id,json=countryId,proto3" json:"country_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProvinceByCodeRequest) Reset() {
	*x = GetProvinceByCodeRequest{}
	mi := &file_province_v1_province_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProvinceByCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProvinceByCodeRequest) ProtoMessage() {}

func (x *GetProvinceByCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_province_v1_province_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProvinceByCodeRequest.ProtoReflect.Descriptor instead.
func (*GetProvinceByCodeRequest) Descriptor() ([]byte, []int) {
	return file_province_v1_province_proto_rawDescGZIP(), []int{8}
}

func (x *GetProvinceByCodeRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *GetProvinceByCodeRequest) GetCountryId() string {
	if x != nil {
		return x.CountryId
	}
	return ""
}

type GetProvinceByCodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Province      *Province              `protobuf:"bytes,1,opt,name=province,proto3" json:"province,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProvinceByCodeResponse) Reset() {
	*x = GetProvinceByCodeResponse{}
	mi := &file_province_v1_province_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProvinceByCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProvinceByCodeResponse) ProtoMessage() {}

func (x *GetProvinceByCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_province_v1_province_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProvinceByCodeResponse.ProtoReflect.Descriptor instead.
func (*GetProvinceByCodeResponse) Descriptor() ([]byte, []int) {
	return file_province_v1_province_proto_rawDescGZIP(), []int{9}
}

func (x *GetProvinceByCodeResponse) GetProvince() *Province {
	if x != nil {
		return x.Province
	}
	return nil
}

type ListProvincesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Search        string                 `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	CountryId     string                 `protobuf:"bytes,4,opt,name=country_id,json=countryId,proto3" json:"country_id,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Code          string                 `protobuf:"bytes,7,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProvincesRequest) Reset() {
	*x = ListProvincesRequest{}
	mi := &file_province_v1_province_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProvincesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProvincesRequest) ProtoMessage() {}

func (x *ListProvincesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_province_v1_province_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProvincesRequest.ProtoReflect.Descriptor instead.
func (*ListProvincesRequest) Descriptor() ([]byte, []int) {
	return file_province_v1_province_proto_rawDescGZIP(), []int{10}
}

func (x *ListProvincesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListProvincesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListProvincesRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *ListProvincesRequest) GetCountryId() string {
	if x != nil {
		return x.CountryId
	}
	return ""
}

func (x *ListProvincesRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ListProvincesRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListProvincesRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type ListProvincesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provinces     []*Province            `protobuf:"bytes,1,rep,name=provinces,proto3" json:"provinces,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProvincesResponse) Reset() {
	*x = ListProvincesResponse{}
	mi := &file_province_v1_province_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProvincesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProvincesResponse) ProtoMessage() {}

func (x *ListProvincesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_province_v1_province_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProvincesResponse.ProtoReflect.Descriptor instead.
func (*ListProvincesResponse) Descriptor() ([]byte, []int) {
	return file_province_v1_province_proto_rawDescGZIP(), []int{11}
}

func (x *ListProvincesResponse) GetProvinces() []*Province {
	if x != nil {
		return x.Provinces
	}
	return nil
}

func (x *ListProvincesResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ListProvincesByCountryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CountryId     string                 `protobuf:"bytes,1,opt,name=country_id,json=countryId,proto3" json:"country_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProvincesByCountryRequest) Reset() {
	*x = ListProvincesByCountryRequest{}
	mi := &file_province_v1_province_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProvincesByCountryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProvincesByCountryRequest) ProtoMessage() {}

func (x *ListProvincesByCountryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_province_v1_province_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProvincesByCountryRequest.ProtoReflect.Descriptor instead.
func (*ListProvincesByCountryRequest) Descriptor() ([]byte, []int) {
	return file_province_v1_province_proto_rawDescGZIP(), []int{12}
}

func (x *ListProvincesByCountryRequest) GetCountryId() string {
	if x != nil {
		return x.CountryId
	}
	return ""
}

type ListProvincesByCountryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provinces     []*Province            `protobuf:"bytes,1,rep,name=provinces,proto3" json:"provinces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProvincesByCountryResponse) Reset() {
	*x = ListProvincesByCountryResponse{}
	mi := &file_province_v1_province_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProvincesByCountryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProvincesByCountryResponse) ProtoMessage() {}

func (x *ListProvincesByCountryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_province_v1_province_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProvincesByCountryResponse.ProtoReflect.Descriptor instead.
func (*ListProvincesByCountryResponse) Descriptor() ([]byte, []int) {
	return file_province_v1_province_proto_rawDescGZIP(), []int{13}
}

func (x *ListProvincesByCountryResponse) GetProvinces() []*Province {
	if x != nil {
		return x.Provinces
	}
	return nil
}

type Province struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CountryId     string                 `protobuf:"bytes,2,opt,name=country_id,json=countryId,proto3" json:"country_id,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	NameEn        string                 `protobuf:"bytes,5,opt,name=name_en,json=nameEn,proto3" json:"name_en,omitempty"`
	Type          string                 `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	Area          float64                `protobuf:"fixed64,7,opt,name=area,proto3" json:"area,omitempty"`
	Population    int64                  `protobuf:"varint,8,opt,name=population,proto3" json:"population,omitempty"`
	Coordinates   string                 `protobuf:"bytes,9,opt,name=coordinates,proto3" json:"coordinates,omitempty"`
	Capital       string                 `protobuf:"bytes,10,opt,name=capital,proto3" json:"capital,omitempty"`
	PostalCode    string                 `protobuf:"bytes,11,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	PhonePrefix   string                 `protobuf:"bytes,12,opt,name=phone_prefix,json=phonePrefix,proto3" json:"phone_prefix,omitempty"`
	SortOrder     int32                  `protobuf:"varint,13,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	Status        string                 `protobuf:"bytes,14,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,16,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,17,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	UpdatedBy     string                 `protobuf:"bytes,18,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Province) Reset() {
	*x = Province{}
	mi := &file_province_v1_province_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Province) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Province) ProtoMessage() {}

func (x *Province) ProtoReflect() protoreflect.Message {
	mi := &file_province_v1_province_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Province.ProtoReflect.Descriptor instead.
func (*Province) Descriptor() ([]byte, []int) {
	return file_province_v1_province_proto_rawDescGZIP(), []int{14}
}

func (x *Province) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Province) GetCountryId() string {
	if x != nil {
		return x.CountryId
	}
	return ""
}

func (x *Province) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Province) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Province) GetNameEn() string {
	if x != nil {
		return x.NameEn
	}
	return ""
}

func (x *Province) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Province) GetArea() float64 {
	if x != nil {
		return x.Area
	}
	return 0
}

func (x *Province) GetPopulation() int64 {
	if x != nil {
		return x.Population
	}
	return 0
}

func (x *Province) GetCoordinates() string {
	if x != nil {
		return x.Coordinates
	}
	return ""
}

func (x *Province) GetCapital() string {
	if x != nil {
		return x.Capital
	}
	return ""
}

func (x *Province) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

func (x *Province) GetPhonePrefix() string {
	if x != nil {
		return x.PhonePrefix
	}
	return ""
}

func (x *Province) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *Province) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Province) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Province) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Province) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *Province) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

var File_province_v1_province_proto protoreflect.FileDescriptor

const file_province_v1_province_proto_rawDesc = "" +
	"\n" +
	"\x1aprovince/v1/province.proto\x12\vprovince.v1\x1a\x1cgoogle/api/annotations.proto\"\xde\x02\n" +
	"\x15CreateProvinceRequest\x12\x1d\n" +
	"\n" +
	"country_id\x18\x01 \x01(\tR\tcountryId\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x17\n" +
	"\aname_en\x18\x04 \x01(\tR\x06nameEn\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\x12\n" +
	"\x04area\x18\x06 \x01(\x01R\x04area\x12\x1e\n" +
	"\n" +
	"population\x18\a \x01(\x03R\n" +
	"population\x12 \n" +
	"\vcoordinates\x18\b \x01(\tR\vcoordinates\x12\x18\n" +
	"\acapital\x18\t \x01(\tR\acapital\x12\x1f\n" +
	"\vpostal_code\x18\n" +
	" \x01(\tR\n" +
	"postalCode\x12!\n" +
	"\fphone_prefix\x18\v \x01(\tR\vphonePrefix\x12\x1d\n" +
	"\n" +
	"sort_order\x18\f \x01(\x05R\tsortOrder\"K\n" +
	"\x16CreateProvinceResponse\x121\n" +
	"\bprovince\x18\x01 \x01(\v2\x15.province.v1.ProvinceR\bprovince\"\x86\x03\n" +
	"\x15UpdateProvinceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"country_id\x18\x02 \x01(\tR\tcountryId\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x17\n" +
	"\aname_en\x18\x05 \x01(\tR\x06nameEn\x12\x12\n" +
	"\x04type\x18\x06 \x01(\tR\x04type\x12\x12\n" +
	"\x04area\x18\a \x01(\x01R\x04area\x12\x1e\n" +
	"\n" +
	"population\x18\b \x01(\x03R\n" +
	"population\x12 \n" +
	"\vcoordinates\x18\t \x01(\tR\vcoordinates\x12\x18\n" +
	"\acapital\x18\n" +
	" \x01(\tR\acapital\x12\x1f\n" +
	"\vpostal_code\x18\v \x01(\tR\n" +
	"postalCode\x12!\n" +
	"\fphone_prefix\x18\f \x01(\tR\vphonePrefix\x12\x1d\n" +
	"\n" +
	"sort_order\x18\r \x01(\x05R\tsortOrder\x12\x16\n" +
	"\x06status\x18\x0e \x01(\tR\x06status\"K\n" +
	"\x16UpdateProvinceResponse\x121\n" +
	"\bprovince\x18\x01 \x01(\v2\x15.province.v1.ProvinceR\bprovince\"'\n" +
	"\x15DeleteProvinceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"2\n" +
	"\x16DeleteProvinceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"$\n" +
	"\x12GetProvinceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"H\n" +
	"\x13GetProvinceResponse\x121\n" +
	"\bprovince\x18\x01 \x01(\v2\x15.province.v1.ProvinceR\bprovince\"M\n" +
	"\x18GetProvinceByCodeRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x1d\n" +
	"\n" +
	"country_id\x18\x02 \x01(\tR\tcountryId\"N\n" +
	"\x19GetProvinceByCodeResponse\x121\n" +
	"\bprovince\x18\x01 \x01(\v2\x15.province.v1.ProvinceR\bprovince\"\xbe\x01\n" +
	"\x14ListProvincesRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06search\x18\x03 \x01(\tR\x06search\x12\x1d\n" +
	"\n" +
	"country_id\x18\x04 \x01(\tR\tcountryId\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x12\n" +
	"\x04code\x18\a \x01(\tR\x04code\"b\n" +
	"\x15ListProvincesResponse\x123\n" +
	"\tprovinces\x18\x01 \x03(\v2\x15.province.v1.ProvinceR\tprovinces\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\">\n" +
	"\x1dListProvincesByCountryRequest\x12\x1d\n" +
	"\n" +
	"country_id\x18\x01 \x01(\tR\tcountryId\"U\n" +
	"\x1eListProvincesByCountryResponse\x123\n" +
	"\tprovinces\x18\x01 \x03(\v2\x15.province.v1.ProvinceR\tprovinces\"\xf5\x03\n" +
	"\bProvince\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"country_id\x18\x02 \x01(\tR\tcountryId\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x17\n" +
	"\aname_en\x18\x05 \x01(\tR\x06nameEn\x12\x12\n" +
	"\x04type\x18\x06 \x01(\tR\x04type\x12\x12\n" +
	"\x04area\x18\a \x01(\x01R\x04area\x12\x1e\n" +
	"\n" +
	"population\x18\b \x01(\x03R\n" +
	"population\x12 \n" +
	"\vcoordinates\x18\t \x01(\tR\vcoordinates\x12\x18\n" +
	"\acapital\x18\n" +
	" \x01(\tR\acapital\x12\x1f\n" +
	"\vpostal_code\x18\v \x01(\tR\n" +
	"postalCode\x12!\n" +
	"\fphone_prefix\x18\f \x01(\tR\vphonePrefix\x12\x1d\n" +
	"\n" +
	"sort_order\x18\r \x01(\x05R\tsortOrder\x12\x16\n" +
	"\x06status\x18\x0e \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x0f \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x10 \x01(\tR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"created_by\x18\x11 \x01(\tR\tcreatedBy\x12\x1d\n" +
	"\n" +
	"updated_by\x18\x12 \x01(\tR\tupdatedBy2\x9a\a\n" +
	"\x0fProvinceService\x12w\n" +
	"\x0eCreateProvince\x12\".province.v1.CreateProvinceRequest\x1a#.province.v1.CreateProvinceResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/api/v1/provinces\x12|\n" +
	"\x0eUpdateProvince\x12\".province.v1.UpdateProvinceRequest\x1a#.province.v1.UpdateProvinceResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\x1a\x16/api/v1/provinces/{id}\x12y\n" +
	"\x0eDeleteProvince\x12\".province.v1.DeleteProvinceRequest\x1a#.province.v1.DeleteProvinceResponse\"\x1e\x82\xd3\xe4\x93\x02\x18*\x16/api/v1/provinces/{id}\x12p\n" +
	"\vGetProvince\x12\x1f.province.v1.GetProvinceRequest\x1a .province.v1.GetProvinceResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/api/v1/provinces/{id}\x12\x89\x01\n" +
	"\x11GetProvinceByCode\x12%.province.v1.GetProvinceByCodeRequest\x1a&.province.v1.GetProvinceByCodeResponse\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/api/v1/provinces/code/{code}\x12q\n" +
	"\rListProvinces\x12!.province.v1.ListProvincesRequest\x1a\".province.v1.ListProvincesResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/api/v1/provinces\x12\xa3\x01\n" +
	"\x16ListProvincesByCountry\x12*.province.v1.ListProvincesByCountryRequest\x1a+.province.v1.ListProvincesByCountryResponse\"0\x82\xd3\xe4\x93\x02*\x12(/api/v1/countries/{country_id}/provincesB7Z5github.com/go-kratos/kratos-layout/api/province/v1;v1b\x06proto3"

var (
	file_province_v1_province_proto_rawDescOnce sync.Once
	file_province_v1_province_proto_rawDescData []byte
)

func file_province_v1_province_proto_rawDescGZIP() []byte {
	file_province_v1_province_proto_rawDescOnce.Do(func() {
		file_province_v1_province_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_province_v1_province_proto_rawDesc), len(file_province_v1_province_proto_rawDesc)))
	})
	return file_province_v1_province_proto_rawDescData
}

var file_province_v1_province_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_province_v1_province_proto_goTypes = []any{
	(*CreateProvinceRequest)(nil),          // 0: province.v1.CreateProvinceRequest
	(*CreateProvinceResponse)(nil),         // 1: province.v1.CreateProvinceResponse
	(*UpdateProvinceRequest)(nil),          // 2: province.v1.UpdateProvinceRequest
	(*UpdateProvinceResponse)(nil),         // 3: province.v1.UpdateProvinceResponse
	(*DeleteProvinceRequest)(nil),          // 4: province.v1.DeleteProvinceRequest
	(*DeleteProvinceResponse)(nil),         // 5: province.v1.DeleteProvinceResponse
	(*GetProvinceRequest)(nil),             // 6: province.v1.GetProvinceRequest
	(*GetProvinceResponse)(nil),            // 7: province.v1.GetProvinceResponse
	(*GetProvinceByCodeRequest)(nil),       // 8: province.v1.GetProvinceByCodeRequest
	(*GetProvinceByCodeResponse)(nil),      // 9: province.v1.GetProvinceByCodeResponse
	(*ListProvincesRequest)(nil),           // 10: province.v1.ListProvincesRequest
	(*ListProvincesResponse)(nil),          // 11: province.v1.ListProvincesResponse
	(*ListProvincesByCountryRequest)(nil),  // 12: province.v1.ListProvincesByCountryRequest
	(*ListProvincesByCountryResponse)(nil), // 13: province.v1.ListProvincesByCountryResponse
	(*Province)(nil),                       // 14: province.v1.Province
}
var file_province_v1_province_proto_depIdxs = []int32{
	14, // 0: province.v1.CreateProvinceResponse.province:type_name -> province.v1.Province
	14, // 1: province.v1.UpdateProvinceResponse.province:type_name -> province.v1.Province
	14, // 2: province.v1.GetProvinceResponse.province:type_name -> province.v1.Province
	14, // 3: province.v1.GetProvinceByCodeResponse.province:type_name -> province.v1.Province
	14, // 4: province.v1.ListProvincesResponse.provinces:type_name -> province.v1.Province
	14, // 5: province.v1.ListProvincesByCountryResponse.provinces:type_name -> province.v1.Province
	0,  // 6: province.v1.ProvinceService.CreateProvince:input_type -> province.v1.CreateProvinceRequest
	2,  // 7: province.v1.ProvinceService.UpdateProvince:input_type -> province.v1.UpdateProvinceRequest
	4,  // 8: province.v1.ProvinceService.DeleteProvince:input_type -> province.v1.DeleteProvinceRequest
	6,  // 9: province.v1.ProvinceService.GetProvince:input_type -> province.v1.GetProvinceRequest
	8,  // 10: province.v1.ProvinceService.GetProvinceByCode:input_type -> province.v1.GetProvinceByCodeRequest
	10, // 11: province.v1.ProvinceService.ListProvinces:input_type -> province.v1.ListProvincesRequest
	12, // 12: province.v1.ProvinceService.ListProvincesByCountry:input_type -> province.v1.ListProvincesByCountryRequest
	1,  // 13: province.v1.ProvinceService.CreateProvince:output_type -> province.v1.CreateProvinceResponse
	3,  // 14: province.v1.ProvinceService.UpdateProvince:output_type -> province.v1.UpdateProvinceResponse
	5,  // 15: province.v1.ProvinceService.DeleteProvince:output_type -> province.v1.DeleteProvinceResponse
	7,  // 16: province.v1.ProvinceService.GetProvince:output_type -> province.v1.GetProvinceResponse
	9,  // 17: province.v1.ProvinceService.GetProvinceByCode:output_type -> province.v1.GetProvinceByCodeResponse
	11, // 18: province.v1.ProvinceService.ListProvinces:output_type -> province.v1.ListProvincesResponse
	13, // 19: province.v1.ProvinceService.ListProvincesByCountry:output_type -> province.v1.ListProvincesByCountryResponse
	13, // [13:20] is the sub-list for method output_type
	6,  // [6:13] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_province_v1_province_proto_init() }
func file_province_v1_province_proto_init() {
	if File_province_v1_province_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_province_v1_province_proto_rawDesc), len(file_province_v1_province_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_province_v1_province_proto_goTypes,
		DependencyIndexes: file_province_v1_province_proto_depIdxs,
		MessageInfos:      file_province_v1_province_proto_msgTypes,
	}.Build()
	File_province_v1_province_proto = out.File
	file_province_v1_province_proto_goTypes = nil
	file_province_v1_province_proto_depIdxs = nil
}
