// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.0
// - protoc             v6.33.1
// source: province/v1/province.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationProvinceServiceCreateProvince = "/province.v1.ProvinceService/CreateProvince"
const OperationProvinceServiceDeleteProvince = "/province.v1.ProvinceService/DeleteProvince"
const OperationProvinceServiceGetProvince = "/province.v1.ProvinceService/GetProvince"
const OperationProvinceServiceGetProvinceByCode = "/province.v1.ProvinceService/GetProvinceByCode"
const OperationProvinceServiceListProvinces = "/province.v1.ProvinceService/ListProvinces"
const OperationProvinceServiceListProvincesByCountry = "/province.v1.ProvinceService/ListProvincesByCountry"
const OperationProvinceServiceUpdateProvince = "/province.v1.ProvinceService/UpdateProvince"

type ProvinceServiceHTTPServer interface {
	// CreateProvince Commands
	CreateProvince(context.Context, *CreateProvinceRequest) (*CreateProvinceResponse, error)
	DeleteProvince(context.Context, *DeleteProvinceRequest) (*DeleteProvinceResponse, error)
	// GetProvince Queries
	GetProvince(context.Context, *GetProvinceRequest) (*GetProvinceResponse, error)
	GetProvinceByCode(context.Context, *GetProvinceByCodeRequest) (*GetProvinceByCodeResponse, error)
	ListProvinces(context.Context, *ListProvincesRequest) (*ListProvincesResponse, error)
	ListProvincesByCountry(context.Context, *ListProvincesByCountryRequest) (*ListProvincesByCountryResponse, error)
	UpdateProvince(context.Context, *UpdateProvinceRequest) (*UpdateProvinceResponse, error)
}

func RegisterProvinceServiceHTTPServer(s *http.Server, srv ProvinceServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/api/v1/provinces", _ProvinceService_CreateProvince0_HTTP_Handler(srv))
	r.PUT("/api/v1/provinces/{id}", _ProvinceService_UpdateProvince0_HTTP_Handler(srv))
	r.DELETE("/api/v1/provinces/{id}", _ProvinceService_DeleteProvince0_HTTP_Handler(srv))
	r.GET("/api/v1/provinces/{id}", _ProvinceService_GetProvince0_HTTP_Handler(srv))
	r.GET("/api/v1/provinces/code/{code}", _ProvinceService_GetProvinceByCode0_HTTP_Handler(srv))
	r.GET("/api/v1/provinces", _ProvinceService_ListProvinces0_HTTP_Handler(srv))
	r.GET("/api/v1/countries/{country_id}/provinces", _ProvinceService_ListProvincesByCountry0_HTTP_Handler(srv))
}

func _ProvinceService_CreateProvince0_HTTP_Handler(srv ProvinceServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateProvinceRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProvinceServiceCreateProvince)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateProvince(ctx, req.(*CreateProvinceRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateProvinceResponse)
		return ctx.Result(200, reply)
	}
}

func _ProvinceService_UpdateProvince0_HTTP_Handler(srv ProvinceServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateProvinceRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProvinceServiceUpdateProvince)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateProvince(ctx, req.(*UpdateProvinceRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateProvinceResponse)
		return ctx.Result(200, reply)
	}
}

func _ProvinceService_DeleteProvince0_HTTP_Handler(srv ProvinceServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteProvinceRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProvinceServiceDeleteProvince)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteProvince(ctx, req.(*DeleteProvinceRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteProvinceResponse)
		return ctx.Result(200, reply)
	}
}

func _ProvinceService_GetProvince0_HTTP_Handler(srv ProvinceServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetProvinceRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProvinceServiceGetProvince)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetProvince(ctx, req.(*GetProvinceRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetProvinceResponse)
		return ctx.Result(200, reply)
	}
}

func _ProvinceService_GetProvinceByCode0_HTTP_Handler(srv ProvinceServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetProvinceByCodeRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProvinceServiceGetProvinceByCode)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetProvinceByCode(ctx, req.(*GetProvinceByCodeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetProvinceByCodeResponse)
		return ctx.Result(200, reply)
	}
}

func _ProvinceService_ListProvinces0_HTTP_Handler(srv ProvinceServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListProvincesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProvinceServiceListProvinces)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListProvinces(ctx, req.(*ListProvincesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListProvincesResponse)
		return ctx.Result(200, reply)
	}
}

func _ProvinceService_ListProvincesByCountry0_HTTP_Handler(srv ProvinceServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListProvincesByCountryRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProvinceServiceListProvincesByCountry)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListProvincesByCountry(ctx, req.(*ListProvincesByCountryRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListProvincesByCountryResponse)
		return ctx.Result(200, reply)
	}
}

type ProvinceServiceHTTPClient interface {
	// CreateProvince Commands
	CreateProvince(ctx context.Context, req *CreateProvinceRequest, opts ...http.CallOption) (rsp *CreateProvinceResponse, err error)
	DeleteProvince(ctx context.Context, req *DeleteProvinceRequest, opts ...http.CallOption) (rsp *DeleteProvinceResponse, err error)
	// GetProvince Queries
	GetProvince(ctx context.Context, req *GetProvinceRequest, opts ...http.CallOption) (rsp *GetProvinceResponse, err error)
	GetProvinceByCode(ctx context.Context, req *GetProvinceByCodeRequest, opts ...http.CallOption) (rsp *GetProvinceByCodeResponse, err error)
	ListProvinces(ctx context.Context, req *ListProvincesRequest, opts ...http.CallOption) (rsp *ListProvincesResponse, err error)
	ListProvincesByCountry(ctx context.Context, req *ListProvincesByCountryRequest, opts ...http.CallOption) (rsp *ListProvincesByCountryResponse, err error)
	UpdateProvince(ctx context.Context, req *UpdateProvinceRequest, opts ...http.CallOption) (rsp *UpdateProvinceResponse, err error)
}

type ProvinceServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewProvinceServiceHTTPClient(client *http.Client) ProvinceServiceHTTPClient {
	return &ProvinceServiceHTTPClientImpl{client}
}

// CreateProvince Commands
func (c *ProvinceServiceHTTPClientImpl) CreateProvince(ctx context.Context, in *CreateProvinceRequest, opts ...http.CallOption) (*CreateProvinceResponse, error) {
	var out CreateProvinceResponse
	pattern := "/api/v1/provinces"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationProvinceServiceCreateProvince))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProvinceServiceHTTPClientImpl) DeleteProvince(ctx context.Context, in *DeleteProvinceRequest, opts ...http.CallOption) (*DeleteProvinceResponse, error) {
	var out DeleteProvinceResponse
	pattern := "/api/v1/provinces/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationProvinceServiceDeleteProvince))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetProvince Queries
func (c *ProvinceServiceHTTPClientImpl) GetProvince(ctx context.Context, in *GetProvinceRequest, opts ...http.CallOption) (*GetProvinceResponse, error) {
	var out GetProvinceResponse
	pattern := "/api/v1/provinces/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationProvinceServiceGetProvince))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProvinceServiceHTTPClientImpl) GetProvinceByCode(ctx context.Context, in *GetProvinceByCodeRequest, opts ...http.CallOption) (*GetProvinceByCodeResponse, error) {
	var out GetProvinceByCodeResponse
	pattern := "/api/v1/provinces/code/{code}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationProvinceServiceGetProvinceByCode))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProvinceServiceHTTPClientImpl) ListProvinces(ctx context.Context, in *ListProvincesRequest, opts ...http.CallOption) (*ListProvincesResponse, error) {
	var out ListProvincesResponse
	pattern := "/api/v1/provinces"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationProvinceServiceListProvinces))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProvinceServiceHTTPClientImpl) ListProvincesByCountry(ctx context.Context, in *ListProvincesByCountryRequest, opts ...http.CallOption) (*ListProvincesByCountryResponse, error) {
	var out ListProvincesByCountryResponse
	pattern := "/api/v1/countries/{country_id}/provinces"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationProvinceServiceListProvincesByCountry))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProvinceServiceHTTPClientImpl) UpdateProvince(ctx context.Context, in *UpdateProvinceRequest, opts ...http.CallOption) (*UpdateProvinceResponse, error) {
	var out UpdateProvinceResponse
	pattern := "/api/v1/provinces/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationProvinceServiceUpdateProvince))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
